project:
  type: website
  output-dir: docs

website:
  title: "BIOS² Education resources"
  description: "Educational materials, including links to PDFs, videos, and code to reproduce all of our trainings."
  navbar:
    logo: "Bios2_reverse.png"
    right:
    - text: "Home"
      href: index.html
    - text: "Intensive courses"
      menu:
        - text: "Biodiversity Modelling Summer School 2024"
          href: summer-schools/v2024/BiodiversityModelling2024.html
        - text: "Biodiversity Modelling Summer School 2022"
          href: summer-schools/v2022/BiodiversityModelling2022.html
        - text: "Biodiversity Modelling Summer School 2021"
          href: https://bios2.github.io/biodiversity_modelling_2021/
        - text: "Biodiversity Modelling Summer School 2019"
          href: summer-schools/v2019/BiodiversityModelling2019.html
    - text: "About BIOS²"
      href: https://bios2.usherbrooke.ca/
    - icon: github
      href: https://github.com/bios2/bios2.github.io
    - icon: twitter
      href: https://twitter.com/_bios2
  search:
    location: navbar
    type: textbox
  site-url: https://bios2.github.io
format:
  html:
    theme: flatly
    css: styles.css
execute:
  freeze: auto
editor: source
listing:
  sort-ui: [date, author]
