---
title: "Summer School in Biodiversity Modelling 2021"
listing: BiodiversityModelling
---

<br>
<br>


The Summer School in Biodiversity Modelling will take place from August 16-25, 2021 under the theme:
Evaluating Models from Ecological Data

Led by Pr. Dominique Gravel and Dr. Andrew MacDonald (Université de Sherbrooke). Training focused on problem solving and guest speakers (Professors Timothée Poisot, Pedro Peres-Neto, Sandra Hamel, Marc Bélisle and others).

Online and Hybrid Training. The format of the intensive summer school has been revised to accommodate COVID’s restrictions on travel and large group activities. Activities will be accessible remotely, but local gatherings may be arranged if the situation allows.
Content

The toolbox for the analysis of ecological data is expanding at unprecedented rates and it is almost impossible to track all of the novel methods available. Their high degree of sophistication is also very restricting, limiting their applicability and our appreciation of some innovative studies. It is out of reach to learn each of them and  advanced training in data modelling is by far the best asset to learn about new methods and develop the one’s best suited for an ecological problem. The objective of this course is to train students methods and skills to fit models to ecological data.

The course will introduce notions of probabilities, maximum likelihood and Bayesian modelling. Emphasis will be put on algorithms and computational methods in order to develop abilities to solve a wide range of problems. By the end of the course, students will be able to define their modelling problem, arrange their data properly, develop the equations to describe the phenomenon of interest and evaluate parameters using information based and Bayesian approaches.


Tentative Schedule

August 16, 2021	Probabilities and distributions: know your data, define your problem.
August 18	Maximum likelihood methods: write down equations for your model.
August 20	Optimization algorithms: reveal the capacities of computers to solve complex problems numerically.
August 23	Bayesian statistics: how to properly represent uncertainty in ecological models.
August 25	Sampling algorithms: evaluating posterior distributions by your own.
Format

The course will consist of five one-day sessions alternating with a day off, spread over two weeks.

Short sessions of lectures and exercises will be given in the morning. The emphasis will be on practice under the supervision of the instructors. The afternoon will be organized around one or two higher level problems to be solved. A guest speaker will be offered at the end of the day to provide a perspective on the day’s topic. Students will have the opportunity to continue working on the problem during the break day, and the solution will be provided at the next session.

Instructors will be available during the exercise period and during breaks throughout the day.

Classes will be taught in English, with bilingual support.
