---
title: "Introduction to EDI concepts in a scientific context"
description: |
  A short introduction to EDI concepts in a scientific context.
author:
  - name: Agathe Riallan
    affiliation: Faculté des Sciences à Université de Sherbrooke
  - name: Marie-José Naud
    affiliation: Centre d’études nordiques (CEN)  
categories: 
  - Transversal competencies
  - FR
  - EN
date: 01-22-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

Texte en français [à la suite](#introduction-aux-concepts-edi-en-contexte-scientifique).  

# Introduction to EDI concepts in a scientific context

In 2021, the BIOS2 training program will be holding a series of training and reflection activities on equity, diversity and inclusion issues. The goal is to develop an EDI action plan for the program in order to consolidate a more inclusive, respectful and open environment.

The objectives of this workshop are:

* Define the concepts of equity, diversity and inclusion
* Identify the benefits and challenges of EDI in the university context
* Recongnize how to become an EDI bearer during one’s university career
* Raise awareness of intercultural communication (professional competence of tomorrow)

The workshop is developed by Agathe Riallan, Faculty Coordinator for Equity, Diversity and Inclusion (EDI) at the Faculty of Science, Université de Sherbrooke, in collaboration with Marie-José Naud, Equity, Diversity and Inclusion Advisor and Coordinator at the Centre d’études nordiques (CEN).

<object data="L'equite la Diversite et l'Inclusion_Sciences (BIOS2+_2e cycle - 1h30)_English.pdf" type="application/pdf" style="height:200%;width:100%">
</object>
<br>
<br>
<br>
<br>
<br>

---

# Introduction aux concepts EDI en contexte scientifique

En 2021, nous aurons une série de formations et d’activités de réflexion sur les questions d’équité, diversité et d’inclusion. Notre objectif est de mettre en place un plan d’action EDI pour le programme afin de consolider un environnement plus inclusif, respectueux et ouvert.

Les objectifs de cet ateliers sont:

* Définir les concepts d’équité, de diversité et d’inclusion
* Identifier les avantages et les défis de l’ÉDI en contexte universitaire
* Identifier comment être porteuse ou porteur de l’ÉDI lors de son parcours universitaire 
* Se sensibiliser à la communication interculturelle (compétence professionnelle de demain)

L’atelier est développé par Agathe Riallan, Coordinatrice facultaire de l’Équité, de la Diversité et de l’Inclusion (ÉDI) de la Faculté des Sciences à Université de Sherbrooke, en collaboration avec Marie-José Naud, Conseillère en équité, diversité et inclusion et coordonnatrice au Centre d’études nordiques (CEN).

<object data="L'equite la Diversite et l'Inclusion_Sciences (BIOS2+_2e cycle - 1h30)_Francais.pdf" type="application/pdf" style="height:200%;width:100%">
</object>
<br>
<br>
<br>
<br>

