---
title: "Introduction to EDI concepts in a scientific context"
description: |
  A short introduction to EDI concepts in a scientific context.
author:
  - name: Marie-José Naud
    affiliation: Centre d’études nordiques (CEN)
  - name: Agathe Riallan
    affiliation: Faculté des Sciences à Université de Sherbrooke
categories: 
  - Career
  - EN
date: 01-22-2021
output:
  distill::distill_article:
    self_contained: false
---

In 2021, the BIOS2 trining program will be holding a series of training and reflection activities on equity, diversity and inclusion issues. The goal is to develop an EDI action plan for the program in order to consolidate a more inclusive, respectful and open environment.

The objectives of this workshop are:

* Define the concepts of equity, diversity and inclusion
* Identify the benefits and challenges of EDI in the university context
* Recongnize how to become an EDI bearer during one’s university career
* Raise awareness of intercultural communication (professional competence of tomorrow)

The workshop is developed by Agathe Riallan, Faculty Coordinator for Equity, Diversity and Inclusion (EDI) at the Faculty of Science, Université de Sherbrooke, in collaboration with Marie-José Naud, Equity, Diversity and Inclusion Advisor and Coordinator at the Centre d’études nordiques (CEN).

<object data="L'equite la Diversite et l'Inclusion_Sciences (BIOS2+_2e cycle - 1h30)_English.pdf" type="application/pdf" style="height:200%;width:100%">
</object>
<br>
<br>
<br>
<br>
