---
title: "Sensibilisation aux réalités autochtones et recherche collaborative"
description: |
  Série de deux webinaires sur la sensibilisation aux réalités autochtones et la recherche en collaboration avec les Autochtones, offert du 28 au 30 avril 2020 par Catherine-Alexandra Gagnon, PhD.
categories:
  - Transversal competencies
  - FR
author:
  - name: "Dr Catherine-Alexandra Gagnon"
bibliography: citations.bib
base_url: https://bios2.github.io/
preview: thumb.jpg
date: 2020-04-28
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

# Partie 1 - Sensibilisation aux réalités autochtones

### Objectifs de la formation :

* Améliorer notre compréhension du passé et de ses impacts sur nos relations entre le avec les Peuples Autochtones.  

* Développer des notions et compétences afin d’agir contre les préjugés et le racisme.  

### Durant ce webminaire, nous allons: 

* Faire un survol des événements historiques importants et de leurs impacts à ce jour (Loi sur les Indiens, politiques d’assimilation, les pensionnats, etc.).  

* Acquérir des connaissances sur la terminologie autochtone.  

* Faire un survol de certains procès et contextes légaux et voir comment ils affectent notre travail en territoire autochtone.  

* Dans une optique de réconciliation, faire une prise de conscience des préjugés persistants et discuter de stratégies pour améliorer nos relations avec les communautés.  

# Partie 2 - Recherche en collaboration avec les communautés autochtones

## Objectifs de la formation :

* Entamer une réflexion collective envers nos pratiques de recherche et comment s’engager de manière significative avec les communautés autochtones.

* Développer une meilleure compréhension des perceptions et attentes des communautés envers la recherche et les chercheurs.

## Durant ce webminaire, nous allons: 

* Mieux comprendre la nécessité de prendre en compte les connaissances autochtones dans divers aspects de la gestion environnementale au Canada; 

* Discuter du désir des communauté d’avoir une présence accrue dans le milieu de la recherche : comment faire?

* Aborder et débattre des différentes approches méthodologiques pour établir des ponts en les connaissances autochtones et scientifiques.


# Ressources

### Balados

 <iframe src="https://www.thecanadianencyclopedia.ca/fr/article/serie-de-baladodiffusion-pensionnats-indiens" title="Série de baladodiffusion Pensionnats indiens" height=400></iframe> 

### Lectures, sites internet 

* Truth and Reconciliation Commission Reports

* [Final Report: National Inquiry into Missing and Murdered Indigenous Women and Girls](https://www.rcaanc-cirnac.gc.ca/eng/1448633299414/1534526479029)  

* [Report of the Royal Commission on Aboriginal Peoples](https://www.bac-lac.gc.ca/eng/discover/aboriginal-heritage/royal-commission-aboriginal-peoples/Pages/final-report.aspx)  

* [Mythes et réalités sur les peuples autochtones](http://www.cdpdj.qc.ca/Publications/Mythes-Realites.pdf)

* [Where are the children? Healing the legacy of the residential schools](http://wherearethechildren.ca/en/)  

* [Indigenous Canada (Coursera)](https://www.coursera.org/learn/indigenous-canada)  

* ["Indigenous Writes", by Chelsea Vowel](https://g.co/kgs/W8vAFY)

* "21 things you might not know about the Indian Act: Helping Canadians make reconciliation with Indigenous Peoples a reality."

* [Northern Quebec: Issues, Spaces and Cultures (MOOC Université Laval)](https://www.ulaval.ca/en/academics/mooc-massive-open-online-courses/northern-quebec-issues-spaces-and-cultures)

### Filmographie

#### National Film Board of Canada 
* [Peuples autochtones au Canada (Premières Nations et Métis)](https://www.nfb.ca/subjects/indigenous-peoples-in-canada-first-nations-and-metis/)  

* [Indigenous Peoples in Canada (Inuit)](https://www.nfb.ca/subjects/indigenous-peoples-in-canada-inuit/)  

* [Wapikoni](http://www.wapikoni.ca)  

### Références

[@armitage_co-management_2011]: *Co-managements and the co-production of knowledge: learning to adapt in Canada’s Arctic.*  

[@berkes_sacred_1999]: *Sacred ecology: traditional ecological knowledge and resource management.* ^[A more recent edition exists.]  

[@berkes_evolution_2009]: *Evolution of co-management: role of knowledge generation, bridging organizations and social learning.*  

[@berkes_rediscovery_2000]: *Rediscovery of traditional ecological knowledge as adaptive management.*  

[@gagnon_merging_2020]: *Merging indigenous and scientific knowledge links climate with the growth of a large migratory caribou population.*  

[@gagnon_integrating_2009]: *Integrating traditional ecological knowledge and ecological science: a question of scale.*  

[@gearheard_challenges_2009]: *Challenges in community-research relationships: learning from natural science in Nunavut.*  

[@nickels2006negotiating]: *Negotiating research relationships with Inuit communities: a guide for researchers.*  

[@kendrick2005denesqline]: *Denésqliné (Chipewyan) knowledge of barren-ground caribou (Rangifer tarandus groenlandicus) movements.*  

[@kofinas_towards_2003]: *Towards a protocol for community monitoring of caribou body condition.*  

[@kofinas_g._community_2002]: *Community contributions to ecological monitoring: knowledge co-production in the U.S.-Canada Arctic Borderlands.*  

[@kofinas_research_2000]: *Research planning in the face of change: the human role in reindeer/caribou systems.*  

[@lyver_monitoring_2010]: *Monitoring barren-ground caribou body condition with Denésôåiné traditional knowledge.*  

[@mallory_local_2006]: *Local ecological knowledge of the Sleeper and Split Islands.*  

[@mallory_local_2003]: *Local Ecological Knowledge of Ivory Gull Declines in Arctic Canada.*  

[@ostrom2001social]: *A social science perspective on social capital: social capital and collective action.*

[@plummer_people_2006]: *People matter: the importance of social capital in the co-management of natural resources.*

[@plummer2007connecting]: *Connecting adaptive co-management, social learning, and social capital through theory and practice.*  

[@reid_bridging_2006]: *Bridging scales and knowledge systems: concepts and applications in ecosystem assessment.*  

## Formatrice :

Catherine-Alexandra Gagnon possède une expertise dans le travail collaboratif en milieux autochtones. Elle s’intéresse particulièrement à la mise en commun des savoirs locaux, autochtones et scientifiques. Elle détient un doctorat en Sciences de l’environnement et une maîtrise en Gestion de la faune de l’Université du Québec à Rimouski, un baccalauréat en biologie faunique de l’université McGill ainsi qu’un certificat en Études autochtones de l’université de Montréal. Durant ses études, elle a travaillé sur les connaissances locales et ancestrales des Aîné(e)s et chasseurs Inuit, Inuvialuit et Gwich’in du Nunavut, des Territoires du Nord-Ouest et du Yukon.