---
title: "Science Communication"
description: |
  Recordings, content and handouts from a 6-hour Science Communication workshop held over two days on 15 and 16 June 2020.
author:
  - name: Gracielle Higino
  - name: Katherine Hébert
preview: images/scicomm_training.png
categories: 
  - Training
  - Fellow contributed
  - Six hour
date: 2020-06-15
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



The objective of this training is to share and discuss the concepts and tools that contribute to effective science communication. The training is split into two sessions, which cover the basic concepts of effective science communication and how social media tools can be used to boost the signal of your research and extend your research network. Each training takes the form of a presentation interspersed with several short activity modules, where participants are invited to use the tools we will be discussing to kickstart their own science communication.


This training was given on June 1 and 2, 2020. You can view recordings of each session here:

### Day 1

<iframe width="560" height="315" src="https://www.youtube.com/embed/MJCXqsnlHZg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


Day 2: <https://youtu.be/Xo7bbJpj4PQ><br>


Training materials can be downloaded as "Supporting Data Files" at the top of the page.

Session 1: The basics of science communication

## Objectives:

1. Discuss what science communication (or SciComm) can be, and its potential role in boosting the signal of your research
2. Make an overview of basic concepts and tools that you can use in any medium (blog posts, presentations, conversations, twitter, etc.) to do effective science communication

During this session, we:

1. Discuss the potential pitfalls of science communication (notably, diversity and inclusivity problems).
2. Cover the basic concepts of science communication, including the Golden Circle method, the creation of personas, and storytelling techniques.
3. Have short activities where participants can try to use some of the techniques we will be covering, such as filling in their own Golden Circle and explaining a blog post as a storyboard.

Session 2: Social media as a science communication tool

Objectives:

1. Rethink the way we write about science by exploring the world of blog posts
2. Clarify the mechanics of Twitter and how it can be used effectively for science communication

During this session, we:

1. Discuss how to create a story structure using titles and the flow of ideas in blog posts, especially when we are used to writing scientific articles
2. Cover the basics of how Twitter works (retweets, threads, replies, hashtags, photo captions, etc.) and how to find helpful connections
3. Have short activities where participants will be invited to write their own Twitter biographies and to create a Twitter thread explaining a project of their choice.

