---
title: "Probability for Ecologists"
description: |
  Material covered on Day 1.
author: 
  - name: Dominique Gravel
  - name: Andrew MacDonald
date: 2021-08-16
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


make_url <- function(pres_name){
  paste0("https://bios2.github.io/BiodiversityModelling/01_probabilities/",
         pres_name,
         "/#1")
}


embed_slides <- function(pres_name){
  
  url <- paste0("https://bios2.github.io/BiodiversityModelling/01_probabilities/",
                pres_name,
                "/#1")
  
  iframe <- xaringanExtra::embed_xaringan(url)
  
  lnk <- paste0("[Click to view full screen](", url, ")")
  
  knitr::asis_output(paste0(iframe,"\n", lnk))

}

slide_link <- function(pres_name){
  lnk <- paste0("[Click to view full screen](", make_url(pres_name), ")")
  knitr::asis_output(lnk)
}
```

## Introduction to probability 

```{r}
xaringanExtra::embed_xaringan(make_url("01-introduction"))
slide_link("01-introduction")
```


## Definitions
```{r}
embed_slides("02-definitions")
```



## Rules of probability

```{r}
embed_slides("03-rules")
```


## Solutions

```{r}
embed_slides("05-solutions")
```


## Problem

```{r}
embed_slides("06-problem")
```
