{
  "hash": "451d4b28d224696937c4b5cadfee9f03",
  "result": {
    "markdown": "---\ntitle: \"Generalized Linear Models for Community Ecology\"\ndescription: \"In this workshop we will explore, discuss, and apply generalized linear models to combine information on species distributions, traits, phylogenies, environmental and landscape variation. We will also discuss inference under spatial and phylogenetic autocorrelation under fixed and random effects implementations. We will discuss technical elements and cover implementations using R.\"\nauthor:\n  - name: \"Pedro Peres-Neto\"\n    affiliation: Concordia University\ndate: \"05-17-2021\"\nimage: image.jpg\ncategories: [Technical, EN]\ntoc: true\nnumber-sections: true\nnumber-depth: 1\n---\n\n\n\n\n<span style=\"font-size:2em;\">Generalized Linear Model for Community Ecology</span>       \n\n<span style=\"color:black\">Pedro Peres-Neto, Concordia University</span>                   \n<span style=\"color:black\">BIOS2 workshop, May 17 to 21, 2021</span>  \n<span style=\"color:black\">This document was put together for the first time for this workshop.</span>         \n<span style=\"color:black\">Let me know if you have suggestions or find any issues in the document.</span>    \n<hr style=\"border:1px solid gray\"> </hr>       \n\n<span style=\"color:firebrick\">**Tentative schedule**</span>\n\n* Day 1:        \n  Introduction to types of data and approaches using GLMs in community ecology.            \n  Types of patterns in species distributions involving trait and environmental variation.              \n  Simulating data as a path to understand GLMs in community ecology.               \n  The simplest GLM: widely used bivariate correlations.             \n  The challenges of statistical inference regarding linking different types of information from communities and species.        \n  Understanding estimators and their properties in GLMs.         \n\n* Day 2:       \n  From bivariate correlations to a variety of more complex GLMs: the case of Binomial and Poisson.        \n  The role of latents in specifying GLMs for community ecology.            \n  The issues underlying autocorrelation in ecological data: the cases of spatial and phylogenetic autocorrelation.                \n  Simple GLMM approaches (Generalized Linear Mixed Models).         \n\n* Day 3:        \n  More complex GLMM approaches.                \n  Potential approaches for incorporating intraspecific data on traits.          \n  Discussion with participants: your research interests, your questions or your data (or anything really).\n\n<span style=\"color:firebrick\">**Philosophy:**</span> We can't cover everything with extreme details.  I've chosen a level that should be interesting enough and cover many different important aspects of GLMs applied to community ecology.\n\n<span style=\"color:firebrick\">**Note:**</span> I mostly apply here base functions so that participants without strong knowledge of certain packages (e.g., ggplot, dplyr) can follow the code more easily.  \n\n<span style=\"color:firebrick\">**Questions:**</span> Participants should feel free to ask questions either directly or in the zoom chat. I've also set a good doc where participants can put questions there during the week when we are not connected.  I'll read them and try to provide an answer or cover the question somehow:           \n\n<a href = \"https://docs.google.com/document/d/17GQvGkBFs9MmLv6Yn473_Dr1t1Ps03VdHOHMhbZhBKk/edit\">https://docs.google.com/document/d/17GQvGkBFs9MmLv6Yn473_Dr1t1Ps03VdHOHMhbZhBKk/edit</a>\n\n<hr style=\"border:1px solid gray\"> </hr>           \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Simulating data**</span></div>                   \n\n<span style=\"color:firebrick\">Simulating a single species</span>                   \n\nOne way to develop good intuition underlying quantitative methods is to be able to simulate data according to certain desired characteristics.  We can then apply methods (GLMs here) to see how well they retrieve the data characteristics.     \n\nLet's start with a very simple GLM, the logistic regression for one single species.  Here, for simplicity, we considered one predictor.  In many ecological simulations, this single predictor is considered an \"environmental gradient\" containing many environmental predictors.  We can consider more gradients and we will discuss that later on in the workshop.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100) # so that we all have the same results\nn.sites <- 100\nX <- rnorm(n.sites)\nb0 <- 0.5 # controls the max prob. values\nprob.presence <- 1./(1+exp(-(b0+3*X)))\nplot(prob.presence ~ X)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=576}\n:::\n:::\n\n\nThis model is pretty simple and its form is:\n\n$$p=\\frac{1}{1+e^{-(\\beta_0+\\beta_1X_1)}} = \\frac{1}{1+e^{-(0.5+3X_1)}}$$\n\nNow let's generate presences and absences according to the logistic model expectation.  Since is a logistic model, we use `rbinom`,i.e., binomial trials:\n\n::: {.cell}\n\n```{.r .cell-code}\nDistribution <- rbinom(n.sites,1,prob.presence)\n```\n:::\n\n```\nView(cbind(prob.presence,Distribution))\n```\n\nLet's model the data using logistic regression:\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- glm(Distribution ~ X,family=binomial(link=logit))\ncoefficients(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)           X \n 0.09200133  3.66168492 \n```\n:::\n:::\n\n```\nView(cbind(prob.presence,Distribution,model$fitted.values))\n```\n\nPlotting the predicted versus the observed presence-absence values:\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model$fitted.values ~ Distribution)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=576}\n:::\n:::\n\n\nAt this point, we won't cover model diagnostics.  Data were simulated according to the model and, as such, assumptions hold well. Plus, this is a single-species model; and this workshop is about community data, i.e., multiple species :).\n\n<a href = \"http://www.sthda.com/english/articles/36-classification-methods-essentials/148-logistic-regression-assumptions-and-diagnostics-in-r/\">This is a good blog explaining how to check for assumptions of logistic regressions.</a>\n\n<span style=\"color:firebrick\">Simulating a more realistic single species</span>                           \n\nSpecies don't tend to respond linearly to environmental features:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Gaussian.png){width=50%}\n:::\n:::\n\n\nNow that we understand some basics of presence-absence data, let's concentrate on more realistic species distribution data and multi-species data.  There are many ways (found in the ecological literature) in which we can simulate these type of data. Below we will generate data using a standard Gaussian model for presence-absence data according to a trait and environmental feature (we will cover abundance data later on). This is a commonly used way to simulate data.  Let's start with a single species and one environmental variable.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100) # so that we all have the same results\nn.sites <- 100\nX <- rnorm(n.sites)\noptimum <- 0.2\nniche.breadth <- 0.5\nb0 <- 1 # controls the max prob. values\nb1 <- -2\n# this is a logistic model:\nprob.presence <- 1./(1+exp(-(b0+(b1*(X-optimum)^2)/(2*niche.breadth^2)))) \n```\n:::\n\n\nThis more \"complex\" model has the following form:\n\n$$p=\\frac{1}{1+e^{-(\\beta_0+\\beta_1\\frac{(X-\\mu)^2}{2\\sigma^2})}}=\\frac{1}{1+e^{-(1+2\\frac{(X-0.2)^2}{2\\cdot0.5^2})}}$$\nwhere $\\mu$ represents the species optimum and $\\sigma$ its niche breadth.  \n\nLet's plot these probabilities:\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(X,prob.presence,ylim=c(0,1))\n# plot optimum\nabline(v=optimum,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=576}\n:::\n:::\n\n\nNow let's simulate the distribution, i.e., presences and absences according to the model.  Since is a logistic, we use `rbinom`,i.e., binomial trials:\n\n::: {.cell}\n\n```{.r .cell-code}\nDistribution <- rbinom(n.sites,1,prob.presence)\n```\n:::\n\n\nPlot the species distribution against the environmental variable:\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(X,prob.presence,ylim=c(0,1))\nsites.present <- which(Distribution==1)\npoints(X[sites.present],Distribution[sites.present],col=\"green\",pch=16,cex=0.5)\nsites.absent <- which(Distribution==0)\npoints(X[sites.absent],Distribution[sites.absent],col=\"red\",pch=16,cex=0.5)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=576}\n:::\n:::\n\n\nThe parameters can be then estimated from the data using a logistic regression:\n\n::: {.cell}\n\n```{.r .cell-code}\npredictor <- cbind(X,X^2) \nmodel <- glm(Distribution ~ predictor,family=binomial(link=logit))\ncoeffs <- coefficients(model)\nb0 <- coeffs[1]\nb1 <- coeffs[2]\nb2 <- coeffs[3]\nestimated.optimum <- -b1/(2*b2) # as in ter Braak and Looman 1986\nestimated.niche.breadth <- 1/sqrt(-2*b2)\nc(estimated.optimum,estimated.niche.breadth) # estimated by the glm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npredictorX  predictor \n 0.3317377  0.3922625 \n```\n:::\n\n```{.r .cell-code}\nc(optimum,niche.breadth) # set in our simulations above\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2 0.5\n```\n:::\n:::\n\n\nWe can demonstrate computationally that the parameter estimations are unbiased as they are maximum likelihood via the GLM.  Here we will be showing the sampling variation only for niche optimum and breadth.  The other two parameters, $\\beta_0$ and $\\beta_1$ can be placed in the code below as well, demonstrating that they are also not biased.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nn.samples <- 1000\nestimation.matrix <- matrix(0,n.samples,2)\ncolnames(estimation.matrix) <- c(\"optimum\",\"niche.breadth\")\n# remember that we already set the parameters for the model above, i.e., optimum and niche breadth\nfor (i in 1:n.samples){\n   X <- rnorm(n.sites)\n   prob.presence <- 1./(1+exp((-b0+((X-optimum)^2)/(2*niche.breadth^2)))) # this is a logistic model\n   Distribution <- rbinom(n.sites,1,prob.presence)\n   predictor <- cbind(X,X^2) \n   model <- glm(Distribution ~ predictor,family=binomial(link=logit))\n   coeffs <- coefficients(model)\n   intercept <- coeffs[1]\n   b1 <- coeffs[2]\n   b2 <- coeffs[3]\n   estimation.matrix[i,\"optimum\"] <- -b1/(2*b2)\n   estimation.matrix[i,\"niche.breadth\"] <- 1/sqrt(-2*b2)\n}\n```\n:::\n\nThere may be warnings \"glm.fit: fitted probabilities numerically 0 or 1 occurred\".  But that is not a problem per se. It just tells us that the for some species, their models capture the distribution values perfectly. By the way, that also happens with real data.  \n\nLet's observe the random variation around the parameter estimates and the average values:\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(estimation.matrix)\nabline(h=apply(estimation.matrix,2,mean),col=\"firebrick\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=576}\n:::\n\n```{.r .cell-code}\napply(estimation.matrix,2,mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      optimum niche.breadth \n    0.2016913     0.4834230 \n```\n:::\n\n```{.r .cell-code}\nc(optimum,niche.breadth) # set in our simulations above\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2 0.5\n```\n:::\n:::\n\nNote how the mean values are pretty close to the true values used to generate the data.  This small simulation helps one understand the principles of sampling variation and unbiased estimation.       \n\n<span style=\"color:firebrick\">Simulating multiple species</span>                   \n\nNow, let's generalize our code to multiple species.  We will create a function that allow us to make sure that all sites have at least one species present and all species are present at least in one site; this is a common (but not necessary) characteristic of data used in community ecology.       \n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_communities <- function(tolerance,E,T,n.species,n.communities){\n    repeat {\n        # generates variation in niche breadth across species\n        niche.breadth <- runif(n.species)*tolerance \n        b0 <- runif(n.species,min=-4,max=4)\n        prob.presence <- matrix(data=0,nrow=n.communities,ncol=n.species)\n        Dist.matrix <- matrix(data=0,nrow=n.communities,ncol=n.species)\n        for(j in 1:n.species){\n          # species optima are trait values; which makes sense ecologically\n          prob.presence[,j] <- 1./(1+exp((-b0[j]+((E-T[j])^2)/(2*niche.breadth[j]^2)))) \n          Dist.matrix[,j] <- rbinom(n.communities,1,prob.presence[,j])\n        }\n        n_species_c <- sum(colSums(Dist.matrix)!=0) # _c for check\n        n_communities_c <- sum(rowSums(Dist.matrix)!=0)\n        if ((n_species_c == n.species) & (n_communities_c==n.communities)){break}\n    }\n    result <- list(Dist.matrix=Dist.matrix,prob.presence=prob.presence)\n    return(result)\n}\n```\n:::\n\n\nNow let's generate a community. Note that we are using one environmental gradient and one trait.  We could consider more variables (trait or environmental features) by adding terms to the logistic equation above.  But for the time being, that will suffice.  Note, thout, that in many ecological simulations, this single predictor is considered an \"environmental gradient\" containing many environmental predictors.  We can consider more gradients and we will discuss that later on in the workshop.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12351) # so that we all have the same results\nn.communities <- 100\nn.species <- 50\nE <- rnorm(n.communities)\nT <- rnorm(n.species)\nDist <- generate_communities(tolerance = 1.5, E, T, n.species, n.communities)\nProbs <- Dist$prob.presence\nDistribution <- Dist$Dist.matrix\n```\n:::\n\n\nLet's plot the probability values across environmental values. To do that nicely, we need to order the communities according to their environmental values as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nE.sorted <- sort(E, index.return=TRUE)\nProbs.sorted <- Probs[E.sorted$ix,]\nE.sorted <- E.sorted$x\nmatplot(E.sorted, Probs.sorted, cex.lab=1.5,cex.axis=2,lty = \"solid\", type = \"l\", pch = 1:10, cex = 0.8,\n        xlab = \"Enviroment\", ylab = \"Probability of presence\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=576}\n:::\n:::\n\n\nAnd let's plot presences and absences against ordered environmental and trait values:\n\n::: {.cell}\n\n```{.r .cell-code}\nheatmap(as.matrix(Distribution),scale=\"none\",Rowv=E,Colv=T,col=c(\"white\",\"black\"),labCol=\"species\",labRow=\"communities\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=576}\n:::\n:::\n\n\n<hr style=\"border:1px solid gray\"> </hr>        \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Classic and simple GLMs for one trait and one environment (bivariate correlations)**</span></div>                   \n\nNow that we have a basic understanding of one GLM (logistic) and how they can model different types of community ecology data, i.e., species distributions, traits and environmental variation, we can start looking into approaches that that are used by ecologists to estimate the importance of environmental and trait variation to species distributions.  \n\nLet's start by calculating the simplest and widely used metric of the community weighted trait mean:\n\n::: {.cell}\n\n```{.r .cell-code}\nCWM <- Distribution %*% T / rowSums(Distribution)\n```\n:::\n\nFor data that are based on presence-absence, this is simply the average of species trait values within communities.   \n\nLet's now correlate CWM with the environment, i.e., community weighted means correlation. This is a widely used approach by ecologists:\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(CWM ~ E)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=576}\n:::\n\n```{.r .cell-code}\ncor(CWM,E)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          [,1]\n[1,] 0.9296338\n```\n:::\n:::\n\n\nAgain, the community weighted means correlation is likely the most commonly used approach with 1000s of studies having been published with it.  \n\nAnother approach is to calculate the species weighted environment means and correlate with trait values.  This approach is less common (but still quite used in the ecological literature) and is sometimes referred as to species niche centroid (SNC):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSNC <- t(E %*% Distribution) / colSums(Distribution)\n```\n:::\n\n\nLet's now correlate SNC with species traits:\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(T ~ SNC)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=576}\n:::\n\n```{.r .cell-code}\ncor(T,SNC)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          [,1]\n[1,] 0.7700065\n```\n:::\n:::\n\n\nNote that the two correlations (CWM- and SNC-based) differ.  That's odd as they were both calculated on exactly the same information: the same Species Matrix, Environment and Trait. Peres-Neto, Dray & ter Braak (2017) demonstrated (mathematically) that this issue is related to the fact that although CWM and SNC are based on weights, they don't standardized and correlate them with the proper weights.  CWM is based on averages calculated based on the sum of species (richness or total abundance per community) and SNC is based on averages calculated based on the number of communities in which species are presence (prevalence) or their total abundance.  \n\nBecause of that, we have found (Peres-Neto et al. 2017) a few undesirable properties of these two correlations (CWM and SNC-based correlations). One is that when the correlation is expected to be zero, the sampling variation of these correlations are quite large (i.e., low precision). Let's evaluate this issue:\nBelow we generate data with structure, but then use a false trait completely independent of the original one, thus destroying the link between trait and environmental variation.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(120) # so that we all have the same results\nn.communities <- 100\nn.species <- 50\nn.samples <- 100 # set to larger later\n\nCWM.cor <- as.matrix(0,n.samples)\nfor (i in 1:n.samples){\n  E <- rnorm(n.communities)\n  T <- rnorm(n.species)\n  Dist <- generate_communities(tolerance = 1.5, E, T, n.species, n.communities)\n  T.false <- rnorm(n.species)\n  CWM <- Dist$Dist.matrix %*% T.false / rowSums(Dist$Dist.matrix)\n  CWM.cor[i] <- cor(CWM,E)\n}\n```\n:::\n\n\nLet's plot the correlations:\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(CWM.cor)\nabline(h=mean(CWM.cor),col=\"firebrick\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=576}\n:::\n:::\n\n                                         \nNote that the variation is quite large for correlations based on a random trait (i.e., T.false).  For example, some correlations were greater than 0.7 and smaller than -0.60.  We showed that although the variation is quite large, the expected value is zero; we would need 10000 or more simulations to make `mean(CWM.cor)` approach almost zero.  A similar issue (i.e., large variation, low precision) happens for correlations based on SNO but we won't simulate here for brevity.  One can easily adapt the code above to do so though.  \n\nWe have shown that precision is much increased when using the 4th corner statistic.  Originally described in matrix form by Legendre et al. (1997), we (Peres-Neto et al. 2017) demonstrated that the 4th corner statisticit is a GLM assuming an identity link, i.e., normally distributed residuals.      \n\nThe basis of the 4th corner correlation is that it starts by the standardization of the trait by the sum of their species abundances (or number of sites occupied for presence-absence data), and the standardization of the environment by the sum of their community abundances.  The default standardization (function `scale`) transforms the variable (trait or environment) in a way that its mean and standard deviation are 0 and 1, respectively.  A weighted standardization makes the weighted mean and weighted standard deviation to be 0 and 1, respectively.  \n\nR doesn't have a default function for weighted standardization.  But this can be done using the follow function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandardize_w <- function(X,w){\n   ones <- rep(1,length(w))\n   Xc <- X - ones %*% t(w)%*% X\n   Xc / ones%*%sqrt(t(ones)%*%(Xc*Xc*w)) \n} \n```\n:::\n\n\nLet's get back to the original data used to calculate CWM and SNC based correlations:\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12351) # so that we all have the same results\nn.communities <- 100\nn.species <- 50\nE <- rnorm(n.communities)\nT <- rnorm(n.species)\nDist <- generate_communities(tolerance = 1.5, E, T, n.species, n.communities)\nDistribution <- Dist$Dist.matrix\n```\n:::\n\n\nWe then standardize environment and trait by their respective abundance sums (rows for environment & columns for trait). \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make distribution matrix relative to its total sum; it makes calculations easier\nDist.rel <- Distribution/sum(Distribution)\nWn <- rowSums(Dist.rel)\nWs <- colSums(Dist.rel)\nE.std_w <- standardize_w(E,Wn)\nT.std_w <-  standardize_w(T,Ws)\n```\n:::\n\n\nNote: In the future, include here the calculation of the weighted mean and standard deviation of \nE.std_w and T.std_w to show that they are zero and one, respectively (when weighted).      \n\nWe then calculate the community average trait (weighted standardized) or the species niche centroid (weighted standardized):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCWM.w <- Dist.rel %*% T.std_w / Wn\nSNC.w <- t(E.std_w) %*% Dist.rel / Ws\n```\n:::\n\n\nWe then calculate the weighted correlation between the two vectors above but their appropriate weights. In the case of CWM.w:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# either using weighted correlation:\nt(CWM.w) %*% (E.std_w*Wn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          [,1]\n[1,] 0.2813709\n```\n:::\n\n```{.r .cell-code}\n# or the same value using weighted regression:\nlm(CWM.w ~ E.std_w,weights = Wn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = CWM.w ~ E.std_w, weights = Wn)\n\nCoefficients:\n(Intercept)      E.std_w  \n  8.804e-17    2.814e-01  \n```\n:::\n:::\n\n\nIn the case of SNC.w:\n\n::: {.cell}\n\n```{.r .cell-code}\n# either using weighted correlation:\nSNC.w %*% (T.std_w*Ws)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          [,1]\n[1,] 0.2813709\n```\n:::\n\n```{.r .cell-code}\n# or the same value using weighted regression:\nlm(t(SNC.w)~T.std_w,weights = Ws)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = t(SNC.w) ~ T.std_w, weights = Ws)\n\nCoefficients:\n(Intercept)      T.std_w  \n -5.000e-17    2.814e-01  \n```\n:::\n:::\n\n\nNote that regardless whether SNC or CWM were used, the 4th corner correlation gives the same result, which makes sense mathematically as both correlations use the exact same information.  The reason (again) that the CWM and SNC standard correlation approaches differ is because they don't use appropriate weights in their standardization and weighted correlation. \n\nAnother issue to notice is that the 4th corner values are smaller than their standard CWM values. Whereas the CWM correlation was 0.9296, the 4th corner was 0.2814.  The issue here is that the CWM correlation refers only to the trait variation among communities (trait beta-diversity), whereas the 4th corner refers to the total variation in traits (within, i.e., trait alpha diversity, and among communities, i.e., trait beta-diversity).  This was demonstrated by algebraic proofs in Peres-Neto et al. (2017) but we won't get into these details here.  \n\nThis does bring an interesting point for the analysis of trait in a community ecology context.  The relative trait variation among communities (i.e., total trait beta-diversity) and within communities (i.e., gamma trait diversity) can be estimated as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Among communities \nAmong.Variation <- sum(diag(t(CWM.w)%*%(CWM.w* Wn))) * 100\n# Within communities \nWithin.Variation <- 100 - Among.Variation\nc(Among.Variation,Within.Variation)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  9.460287 90.539713\n```\n:::\n:::\n\n\nThe standard CWM correlation is high because it pertains to only 9.46% of the total variation, whereas the 4th corner correlation pertains to all variation, i.e., both within and among.  As the among communities component become large, the two correlations become somewhat more similar.  \n\nLet's now investigate the sampling properties of the 4th corner correlation as we did above for the CWM correlation, i.e., when the trait-environment correlation is expected to be zero:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(120) # so that we all have the same results and the same communities and traits are generated as before\nn.communities <- 100\nn.species <- 50\nn.samples <- 100 # set to larger later\n\nCWM.4th.cor <- as.matrix(0,n.samples)\nfor (i in 1:n.samples){\n   E <- rnorm(n.communities)\n   T <- rnorm(n.species)\n   Dist <- generate_communities(tolerance = 1.5, E, T, n.species, n.communities)\n   T.false <- rnorm(n.species) # destroys the original generated relationship\n   Dist.rel <- Dist$Dist.matrix/sum(Distribution)\n   Wn <- rowSums(Dist.rel)\n   E.std_w <- standardize_w(E,Wn)\n   T.std_w.false <-  standardize_w(T.false,Ws)\n   CWM.w.false <- Dist.rel %*% T.std_w.false / Wn\n   t(CWM.w.false) %*% (E.std_w*Wn)\n   CWM.4th.cor[i] <- cor(CWM,E)\n}\n```\n:::\n\n\nLet's compare the two statistics:\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(cbind(CWM.cor,CWM.4th.cor))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n                        \nNote how the 4th corner correlation is a much more precise predictor around the true value of zero.\n\n<hr style=\"border:1px solid gray\"> </hr>       \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Statistical hypothesis testing**</span></div>                   \nWe know for a while that the bivariate correlations discussed so far have elevated type I error rates based on parametric testing and under certain permutation schemes (Dray and Legendre 2008; and Dray et al. 2014).  That means that when the statistical null hypothesis of no link between trait and environment will be rejected more often than the preset alpha level (significance level, e.g., 0.05 or 0.01).  More recently, this was also established for more complex models (more on this later). Resolving these issues are challenging and remain a very active field of research.  \n\nThe code so far has helped to build some intuition underlying the different bivariate correlations.  We will now use a more complete utility function that allows calculating these different metrics using one single function.  This function is part of Peres-Neto et al. (2017).\n\nDownload the utility function file:\n\n<a href=\"UtilityFunctions.R\" download>Click here to download it</a>\n\nLoad the functions into R:    \n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"UtilityFunctions.R\")\n```\n:::\n\n\nLet's use the function that calculates a number of the bivariate correlations, which are essentially simple GLMs. \n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(125)\nE <- rnorm(n.communities)\nT <- rnorm(n.species)\nDist <- generate_communities(tolerance = 1.5, E, T, n.species, n.communities)\nTraitEnv.res <- TraitEnvCor(Distribution,E,T, Chessel = TRUE)\nTraitEnv.res\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               CWM.cor               wCWM.cor                SNC.cor \n           0.016601826            0.054714685            0.288779046 \n              wSNC.cor           Fourthcorner         Chessel.4thcor \n           0.039080469            0.006235766            0.015313259 \n Among Wn-variance (%) Within Wn-variance (%) \n           1.298888497           98.701111503 \n```\n:::\n:::\n\n\nIf we want to isolate the 4th corner correlation, we can simply:\n\n::: {.cell}\n\n```{.r .cell-code}\nTraitEnv.res[\"Fourthcorner\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFourthcorner \n 0.006235766 \n```\n:::\n:::\n\n\nLet's now run permutation Model 2, Model 4 and p.max for data without a link between trait and environment.  We first create the data with no link:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(125)\nE <- rnorm(n.communities)\nT <- rnorm(n.species)\nDist <- generate_communities(tolerance = 1.5, E, T, n.species, n.communities)\nDistribution <- Dist$Dist.matrix\nT.false <- rnorm(n.species)\nTraitEnv.res <- TraitEnvCor(Distribution,E,T.false, Chessel = FALSE)\nTraitEnv.res[\"Fourthcorner\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFourthcorner \n  0.04168433 \n```\n:::\n:::\n\n\nNote how the 4th corner correlation is quite low, i.e., 0.0417.  Now let's check this value with permutations:  \n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(125)\nnrepet <- 99\nobs <- TraitEnv.res[\"Fourthcorner\"]\nsim.row <- matrix(0, nrow = nrepet, ncol = 1)\nsim.col <- matrix(0, nrow = nrepet, ncol = 1)\nfor(i in 1:nrepet){\n   per.row <- sample(nrow(Distribution)) # permute communities\n   per.col <- sample(ncol(Distribution)) # permute species\n   sim.row[i] <- TraitEnvCor(Distribution,E[per.row],T.false)[\"Fourthcorner\"]\n   sim.col[i] <- TraitEnvCor(Distribution,E,T.false[per.col])[\"Fourthcorner\"]\n}\npval.row <- (length(which(abs(sim.row) >= abs(obs))) + 1) / (nrepet + 1)\npval.col <- (length(which(abs(sim.col) >= abs(obs))) + 1) / (nrepet + 1)\np.max <- max(pval.row,pval.col)\nc(pval.row,pval.col,p.max)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01 0.47 0.47\n```\n:::\n:::\n\n\nAs we can see, although only environmental features were important but not traits, the row permutation (across commmunities) detected the relationship as significant.  Note, however, that the permutation across species did not. ter Braak et al. (2012) determined that the maximum value between the two p-values (row and column based) assures appropriate type I error rate as expected alpha.\n\nThe function above allows understanding the permutation procedures.  That said, the utility function file has a more complete function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(125)\nCorPermutationTest(Distribution, E, T.false, nrepet = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    cor prow pcol pmax\nCWM.cor      0.36605145 0.01 0.33 0.33\nwCWM.cor     0.28014652 0.01 0.44 0.44\nSNC.cor      0.14836877 0.39 0.36 0.39\nwSNC.cor     0.09492897 0.26 0.47 0.47\nFourthcorner 0.04168433 0.01 0.47 0.47\n```\n:::\n:::\n\n\n<hr style=\"border:1px solid gray\"> </hr>          \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Bivariate correlations in practice**</span></div>      \n\nI hope by now you are convinced that the 4th corner is a more robust metric of bivariate correlation (one trait and one environment). Here we will use the `Aravo` community plant data set (Massif du Grand Gabilier, France; Choler 2005) contained in the package `ade4`.  We provide more explanation on the data in Dray et al. (2012).  Here we will replicate the analysis in that paper.  The data contain species abundances for 82 species distributed into 75 sites.  Sites are described by 6 environmental variables: mean snowmelt date over the period 1997–1999, slope inclination, aspect, index of microscale landform, index of physical disturbance due to cryoturbation and solifluction, and an index of zoogenic disturbance due to trampling and burrowing activities of the Alpine marmot. All variables are quantitative except the landform and zoogenic disturbance indexes that are categorical variables with five and three categories, respectively. And eight quantitative functional traits (i.e., vegetative height, lateral spread, leaf elevation angle, leaf area, leaf thickness, specific leaf area, mass-based leaf nitrogen content, and seed mass) were measured on the 82 most abundant plant species (out of a total of 132 recorded species). \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](aravo.png){width=70%}\n:::\n:::\n\n\nLoad the package and the data:\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"ade4\") in case you don't have it installed\nlibrary(ade4)\ndata(aravo)\ndim(aravo$spe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 75 82\n```\n:::\n\n```{.r .cell-code}\ndim(aravo$env)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 75  6\n```\n:::\n\n```{.r .cell-code}\ndim(aravo$trait)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 82  8\n```\n:::\n:::\n\n\nLet's estimate the 4th corner correlations between each trait and environmental variable. `nrept` is the number of permutations and should be set to a reasonable high number (say 9999). Here we will use 999 to speed calculations. Note that all permutation tests (not only the ones for the 4th corner) include the observed correlation as part of the null distribution (i.e., permuted); hence the use of `nrept` as 999, i.e., 1000 possible permutations (the observed correlation is a possible permutation if we run the test infinite times; which is not possible; so we consider it as default. `modeltype` is set to 6, which is the largest p-value between model 2 permutation (entire communities in the distribution matrix) and model 4 (entire species in the distribution matrix).  The p-max procedure is detailed in ter Braak et. 2012. Finally, p-values are adjusted using the `false discovery rate` for multiple testing.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nfour.comb.aravo.adj <- fourthcorner(aravo$env, aravo$spe,\naravo$traits, modeltype = 6, p.adjust.method.G = \"none\",\np.adjust.method.D = \"fdr\", nrepet = 999)\n```\n:::\n\n\nResults can be retrieved by simply typing:\n```\nfour.comb.aravo \n```\n\nThe 'classic' table of results can be produced as follows. D2 indicates that the 4th corner correlation is to be used between the quantitative variable and each category of the qualitative variables.  Other bivariate metrics of 4th corner association are also described in Dray and Legendre (2008) for qualitative-quantitative associations. In the default plot, blue cells correspond to negative signicant relationships while red cells correspond to positive signicant relationships (this can be modified using the argument col in the function fourthcorner).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(four.comb.aravo.adj, alpha = 0.05, stat = \"D2\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-41-1.png){width=576}\n:::\n:::\n\n\n<hr style=\"border:1px solid gray\"> </hr>          \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Stacking species information as a way to understand how to build more complex GLMs**</span></div>                   \n\nAlthough widely used (1000s of studies published using them), bivariate correlations are the simplest forms of GLMs for community data. That said, the 4th corner correlation can be calculated in a way that allows us (hopefully) to understand how more complex GLMs can be produced.  They allow us understanding species stacking.  Perhaps I should have considered this presentation before the calculations based on weights and standardizations (will inverst in the next version of the workshop). Let's build a small data so that we understand this principle.  Consider a very artificial distribution matrix with 4 communities and 4 species. It was made artificial so that we can understand well its structure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDistribution <- as.matrix(rbind(c(1,1,0,0),c(1,0,0,0),c(0,0,1,1),c(0,0,1,0)))\nDistribution\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3] [,4]\n[1,]    1    1    0    0\n[2,]    1    0    0    0\n[3,]    0    0    1    1\n[4,]    0    0    1    0\n```\n:::\n:::\n\n\nLet's create some traits and environmental features:\n\n::: {.cell}\n\n```{.r .cell-code}\nT <- c(1,2,5,8)\nE <- c(10,12,100,112)\n```\n:::\n\n\nNow let's calculate its 4th corner correlation:\n\n::: {.cell}\n\n```{.r .cell-code}\nTraitEnvCor(Distribution,E,T)[\"Fourthcorner\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFourthcorner \n   0.8902989 \n```\n:::\n:::\n\n\nThe 4th corner correlation is pretty high given the highly structured data. Another way to calculate a 4th corner correlation is by using what we refer to as an \"inflated approach\". This approach allows understanding the structure of stacked information. This figure demonstrates the process and calculation:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](InflatedApproach4thcorner.png){width=80%}\n:::\n:::\n\n\nNext we stack species distributions, environment and trait information:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn.species <- ncol(Distribution)\nn.sites <- nrow(Distribution)\nDist.stacked <- as.vector(Distribution)\nE.stacked <- rep(1, n.species) %x% E\nT.stacked <- T %x% rep(1, n.sites)  \n```\n:::\n\n```\nView(cbind(Dist.stacked,E.stacked,T.stacked))\n```\n\nWe then eliminatate the cells for which the distribution is zero and calculate the correlation:\n\n::: {.cell}\n\n```{.r .cell-code}\nzeros.dist <- which(Dist.stacked==0)\ncor(E.stacked[-zeros.dist],T.stacked[-zeros.dist])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8902989\n```\n:::\n:::\n\n\nNote: perhaps I should have started with this explanation and then move to the more complicated way of using weights. The inflated approach is in fact a way to see how weights are given.  \n\n<hr style=\"border:1px solid gray\"> </hr>            \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Simulating abundance data and understanding link functions in GLMs**</span></div>        \n\n<span style=\"color:firebrick\">Simple model</span>                   \n\nAlthough community ecologists commonly work with presence-absence data, abundance data are also commonly used in many approaches. Here we will use a Poisson model to simulate community data involving species distributions, traits and environment. Although link functions are used in all families of GLMs (poisson, binomial, negative binomial, gamma, etc), we will try to provide an explanation here of what they mean using abundance data.  But the same rationale will apply to all families.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100) # so that we all have the same results\nn.sites <- 100\nX <- rnorm(n.sites)\nb0 <- 0.05\nb1 <- 2\nY <- exp(b0 + b1*X)\nAbundance <- rpois(n.sites,Y)\nplot(Abundance ~ X)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-48-1.png){width=576}\n:::\n:::\n\n\nThis Poisson model has the following form.  Note that multiple predictors can be considered.  Here, for simplicity, we considered one predictor.  Again, in many ecological simulations, this single predictor is considered an \"environmental gradient\" containing many environmental predictors.  We can consider more gradients and we will discuss that later on in the workshop.  \n\n$$Y={e^{(\\beta_0+\\beta_1X_1)}}=e^{(0.05+1.2X_1)}=log(Y)=0.05+1.2X_1$$\nThe model can be estimated as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- glm(Abundance ~ X, family=\"poisson\")\ncoefficients(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)           X \n 0.03095719  2.02323099 \n```\n:::\n\n```{.r .cell-code}\nplot(model$fitted.values ~ Abundance)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-49-1.png){width=576}\n:::\n:::\n\n\nGLMs are linear models because they use link-functions to map non-linear relationships to a linear one. In this way, the link function connects the predictors in a model with the expected (mean) value of the response variable (dependent variable). In other words, the link-functions transforms the response values into new values that can be then regressed using linear approaches (Maximum Likelihood-based approaches and not simple OLS, ordinary least square approaches as in linear regression) against the X values.  As we saw in the first example of the Poisson regression above, the relationship is not linear.  The link-function for the Poisson distribution is `ln` of the response.  Let's understand this point by plotting the log(Y) and X.  Note that Y has no error and Abundance has error (i.e., based on the `rpois`, i.e., poisson trials)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# without error:\nplot(log(Y) ~ X)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-50-1.png){width=576}\n:::\n\n```{.r .cell-code}\n# with error\nplot(log(Abundance) ~ X)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-50-2.png){width=576}\n:::\n:::\n\n\nWhat does the passage \"the link-function connects the predictors in a model with the expected (mean) value of the response variable (dependent variable)\" mean? As you can notice, we used Poisson trials to generate error around the initial Y values. Let's create a 100 possible trials:\n\n::: {.cell}\n\n```{.r .cell-code}\nmult.Y <- replicate(n=100,expr=rpois(n.sites,Y))\n```\n:::\n\n\n```\nView(mult.Y)\n```\n\nEach column in `mult.Y` contains one single trial. This would mimic, for instance, your  error in estimating abundances when sampling real populations and assuming that a Poisson GLM would model your abundances across sites well.  As such, in real data, obviously, we only have one \"trial\".  But this small demonstration hopefully helps you understand what the GLM is trying to estimate via the link-function.          \n\nLet's repeat the predictor `X` 100 times`so that it becomes compatible in size with the multiple trials; and we can then plot them:\n\n::: {.cell}\n\n```{.r .cell-code}\nrep.X <- rep(X, times = 100)\nplot(as.vector(mult.Y) ~ rep.X,pch=16,cex=0.5,col=\"firebrick\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-52-1.png){width=576}\n:::\n:::\n\n\nNote that larger values of abundances tend to have more error under the poisson model (which is also ecologically plausible).   \n\nNow we can understand what the passage \"the link-function connects the predictors in a model with the expected (mean) value of the response\".  Let's first increase the number of trials to 10000 and for each site (for which we have an X value), calculate its mean:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmult.Y <- replicate(n=10000,expr=rpois(n.sites,Y))\nmean.mult.Y <- apply(mult.Y,1,mean)\nplot(mean.mult.Y ~ Y)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-53-1.png){width=576}\n:::\n:::\n\n\nAs we can observe, the mean across all trials (errors) equal the response variable Y, i.e., without error. Hopefully this provides a general understanding of what link functions are.  A similar explanation can be given for the logistic regression (i.e., binomial error).  In there we use a `logit` link function (transformation) instead.\n\n<span style=\"color:firebrick\">Missing predictors in GLMs as a source of error</span> \n\nObviously the fit is great, particularly because we considered all the important predictors in the model.  We don't usually have all predictors in a model and this can be simulated as well.  Considering the following example where two environmental predictors were used to generate the abundance data but only was used in the regression model: \n\n$$p={e^{(\\beta_0+\\beta_1X_1+\\beta_1X_2)}}$$\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100) # so that we all have the same results\nn.sites <- 100\nX <- matrix(rnorm(n.sites*2),n.sites,2)\nb0 <- 2\nb1 <- 0.5\nb2 <- 1.2\nY <- exp(b0 + b1*X[,1] + b1*X[,2]) # there are more direct matricial ways to do that\nAbundance <- rpois(n.sites,Y)\nmodel <- glm(Abundance ~ X[,1], family=\"poisson\")\nmodel\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:  glm(formula = Abundance ~ X[, 1], family = \"poisson\")\n\nCoefficients:\n(Intercept)       X[, 1]  \n     2.0472       0.5294  \n\nDegrees of Freedom: 99 Total (i.e. Null);  98 Residual\nNull Deviance:\t    532.1 \nResidual Deviance: 258.8 \tAIC: 637.7\n```\n:::\n\n```{.r .cell-code}\nplot(model$fitted.values ~ Abundance)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-54-1.png){width=576}\n:::\n\n```{.r .cell-code}\nAIC(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 637.7152\n```\n:::\n:::\n\nNote that the errors around predicted and true values are much greater because only one predictor was included in the GLM even though two predictors were important.  Now considering both predictors:\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- glm(Abundance ~ X, family=\"poisson\")\nmodel\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:  glm(formula = Abundance ~ X, family = \"poisson\")\n\nCoefficients:\n(Intercept)           X1           X2  \n     1.9808       0.5300       0.4931  \n\nDegrees of Freedom: 99 Total (i.e. Null);  97 Residual\nNull Deviance:\t    532.1 \nResidual Deviance: 119 \tAIC: 500\n```\n:::\n\n```{.r .cell-code}\nplot(model$fitted.values ~ Abundance)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-55-1.png){width=576}\n:::\n\n```{.r .cell-code}\nAIC(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 500.0011\n```\n:::\n:::\n\n\nThis is a critical empirical (ecological) consideration because we can't measure everything.  The error is much smaller and, as a consequence, the model fit is much improved (i.e., smaller AIC values) because it considers the two predictors.  It can't be perfect because of the error related to the poisson trials that will always result in random variation (residual variation).  \n\n<span style=\"color:firebrick\">A more realistic Gaussian Poisson model</span>                   \n\nAs for the logistic model, we can also consider a more realistic Poisson model based on a Gaussian distribution:\n\n$$Y={h\\cdot e^{-(\\beta_0+\\beta_1\\frac{(X-\\mu)^2}{2\\sigma^2})}}$$\nAs before, $\\mu$ represents the species optimum and $\\sigma$ its niche breadth. $h$ represents the expected abundance in the optimum environmental value.  Using code to simulate this model for one species; for simplicity, we will set $\\beta_0=0$ and $\\beta_1=1$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(110)\nX <- rnorm(n.sites)\noptimum <- 1.2\nniche.breadth <- 0.5\nh <- 104\nY <- h * exp(-(X-optimum)^2/(2*niche.breadth^2))\nAbundance <- rpois(n.sites,Y)\nplot(Abundance~X)\nabline(v=1.2,col=\"firebrick\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-56-1.png){width=576}\n:::\n:::\n\n\nLet's fit the Poisson model:\n\n::: {.cell}\n\n```{.r .cell-code}\npredictor <- cbind(X,X^2) \nmodel <- glm(Abundance ~ predictor,family=\"poisson\")\nplot(model$fitted ~ X)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-57-1.png){width=576}\n:::\n\n```{.r .cell-code}\ncoeffs <- coefficients(model)\n```\n:::\n\n\nAs before, parameters used to simulate the species distribution can be estimated as:\n\n::: {.cell}\n\n```{.r .cell-code}\nb0 <- coeffs[1]\nb1 <- coeffs[2]\nb2 <- coeffs[3]\nestimated.optimum <- -b1/(2*b2) \nestimated.niche.breadth <- 1/sqrt(-2*b2)\nh <- exp(b0 + b1*estimated.optimum + b2*estimated.optimum^2)\ncbind(estimated.optimum,estimated.niche.breadth,h)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           estimated.optimum estimated.niche.breadth        h\npredictorX          1.179753               0.4726181 104.8035\n```\n:::\n:::\n\n\nNow we can generalize the code to generate abundance data for multiple species:\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_community_abundance <- function(tolerance,E,T,preset_nspecies,preset_ncommunities){\n    repeat {\n        # one trait, one environmental variable\n        h <- runif(preset_nspecies,min=0.3,max=1)\n        sigma <- runif(preset_nspecies)*tolerance\n        L <- matrix(data=0,nrow=preset_ncommunities,ncol=preset_nspecies)\n        for(j in 1:preset_nspecies){\n            L[,j] <- 30*h[j]*exp(-(E-T[j])^2/(2*sigma[j]^2))\n              #rpois(preset_ncommunities,30*h[j]*exp(-(E-T[j])^2/(2*sigma[j]^2)))\n        }\n        n_species_c <- sum(colSums(L)!=0) # _c for check\n        n_communities_c <- sum(rowSums(L)!=0)\n        if ((n_species_c == preset_nspecies) & (n_communities_c==preset_ncommunities)){break}\n    }\n    return(L)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(120) # so that we all have the same results\nn.communities <- 100\nn.species <- 50\nE <- rnorm(n.communities)\nT <- rnorm(n.species)\nY <- generate_community_abundance(tolerance = 1.5, E, T, n.species, n.communities)\n```\n:::\n\n\nLet's plot the expected abundance values across environmental values. To do that nicely, we need to order the communities according to their environmental values as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nE.sorted <- sort(E, index.return=TRUE)\nY.sorted <- Y[E.sorted$ix,]\nE.sorted <- E.sorted$x\nmatplot(E.sorted, Y.sorted, cex.lab=1.5,cex.axis=2,lty = \"solid\", type = \"l\", pch = 1:10, cex = 0.8,\n        xlab = \"Enviroment\", ylab = \"Abundance\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-61-1.png){width=576}\n:::\n:::\n\n\nY, however, has no error and to create abundance values for each species (i.e., each column of Y; MARGIN = 2) according to a poisson model we can simply:\n\n::: {.cell}\n\n```{.r .cell-code}\nAbundances <- apply(Y,MARGIN=2,function(x) rpois(n.communities,x))\n```\n:::\n\n\nLet's plot the abundance values across environmental values. With erorr, they don't look as nice, obviously:\n\n::: {.cell}\n\n```{.r .cell-code}\nE.sorted <- sort(E, index.return=TRUE)\nAbundances.sorted <- Abundances[E.sorted$ix,]\nE.sorted <- E.sorted$x\nmatplot(E.sorted, Abundances.sorted, cex.lab=1.5,cex.axis=2,lty = \"solid\", type = \"l\", pch = 1:10, cex = 0.8, xlab = \"Enviroment\", ylab = \"Abundance\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-63-1.png){width=576}\n:::\n:::\n\n\nFinally, let's calculate the 4th corner statistics for these data:\n\n::: {.cell}\n\n```{.r .cell-code}\nTraitEnvCor(Abundances,E,T, Chessel = TRUE)[\"Fourthcorner\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFourthcorner \n   0.5365449 \n```\n:::\n:::\n\n\nAnd now for the data without error, i.e., before the poisson trials:\n\n::: {.cell}\n\n```{.r .cell-code}\nTraitEnvCor(Y,E,T, Chessel = TRUE)[\"Fourthcorner\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFourthcorner \n   0.5333836 \n```\n:::\n:::\n\nDespite the error we observed once we transformed Y (values without error) into abundances (with error via the poisson trials), the bivariate correlations are pretty similar, indicating that these metrics are robust against sampling error in abundances.  Note, however, that we only used one predictor which was the one used to simulate the data to begin with; empirical data are much more complex than that.  \n\nFinally, note that, as such, bivariate correlations are calculated in the same way regardless if the data are presence-absence or abundance; biomass data could be also considered.  \n\n<hr style=\"border:1px solid gray\"> </hr>       \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Moving to more complex GLMs - the bilinear model**</span></div>          \n\nLet's go back to our stacked model:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](bilinear.png){width=80%}\n:::\n:::\n\n\nAnd now let's get back to our stacked approach using again the simplest example we used earlier.  Let's enter the data again to make sure that we have the same data.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nDistribution <- as.matrix(rbind(c(1,1,0,0),c(1,0,0,0),c(0,0,1,1),c(0,0,1,0)))\nT <- c(1,2,5,8)\nE <- c(10,12,100,112)\nn.species <- ncol(Distribution)\nn.sites <- nrow(Distribution)\nDist.stacked <- as.vector(Distribution)\nE.stacked <- rep(1, n.species) %x% scale(E)\nT.stacked <- scale(T) %x% rep(1, n.sites)\n```\n:::\n\n\nThere are two ways in which we can code the analysis.  Using the stacked way or using a kronecker product.  The kronecker product stacks the data in the same way but it's a bit more \"cryptic\" and demonstrating the stacking is then easier by using simple coding.  The stacked GLM below estimates the statistical interaction between Environment and Traits only.  Note that the distribution for our ficitional example above is for presence and absences, hence we will use a binomial link-function (i.e., logistic regression).  This can be referred as to the bilinear model by Gabriel (1998) which is rarely used in ecology but can provide a good introduction to what \"stacking\" means which is critical to understand more complex GLMs.  \n\nUsing the stacked vectors above, we have:\n\n::: {.cell}\n\n```{.r .cell-code}\n predictor <- E.stacked * T.stacked\n model <- glm(Dist.stacked ~ predictor,family=binomial(link=logit))\n summary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Dist.stacked ~ predictor, family = binomial(link = logit))\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.1282  -0.5101  -0.2570   0.7417   1.3162  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)  \n(Intercept)  -0.9160     0.7681  -1.193   0.2330  \npredictor     2.4991     1.1975   2.087   0.0369 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 21.170  on 15  degrees of freedom\nResidual deviance: 13.597  on 14  degrees of freedom\nAIC: 17.597\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n:::\n\n\nThe stacking we saw can be easily done using matrix algebra (the early presentation is helpful to understand the principles though).  To do it in algebra, we use the kronecker product as follows:\n\n$$Y= T\\otimes E$$\n\nAs such, the bilinear model is testing the statistical interaction between traits and environmental variables.  \n\nwhich in R becomes:\n\n::: {.cell}\n\n```{.r .cell-code}\npredictor2 <- T %x% E\nmodel <- glm(Dist.stacked ~ predictor,family=binomial(link=logit))\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Dist.stacked ~ predictor, family = binomial(link = logit))\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.1282  -0.5101  -0.2570   0.7417   1.3162  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)  \n(Intercept)  -0.9160     0.7681  -1.193   0.2330  \npredictor     2.4991     1.1975   2.087   0.0369 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 21.170  on 15  degrees of freedom\nResidual deviance: 13.597  on 14  degrees of freedom\nAIC: 17.597\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n:::\n\nNote that the two ways to run the model results in the exact same estimates.  Here we should interpret the slope for the model as the strength between trait and environment, i.e., $\\beta_1 = 2.4991$. Obviously the bilinear model can be easily extended to any class of GLMs as well depending on the nature of the response variable (e.g., poisson, negative binomial, etc; more on these below).\n\nNote also that we could have considered multiple traits and environments (as long as we have enough degrees of freedom).   \n\n<span style=\"color:firebrick\">Stacked or bilinear model on the Aravo data set</span>                   \n\nLet's apply the Aravo data set we saw early here. We will reduce the environmental matrix by removing the qualitative variables.  These can be easily accommodated but for the sake of speed, we will reduce it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- aravo$env[,c(\"Aspect\",\"Slope\",\"Snow\")]\nE <- as.matrix(E)\nT <- as.matrix(aravo$trait)\n```\n:::\n\n\nNow we apply the kronecker product using the base function `kronecker` rather than `%x%` that we saw early.  This function generate names for each column of the matrix (i.e., interactions between each trait and predictor). The columns contain all possible two by two (pairwise) combinations of traits and environmental features.  \n\n::: {.cell}\n\n```{.r .cell-code}\nTE <- kronecker(T, E, make.dimnames = TRUE)\ndim(TE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6150   24\n```\n:::\n\n```{.r .cell-code}\ncolnames(TE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Height:Aspect\" \"Height:Slope\"  \"Height:Snow\"   \"Spread:Aspect\"\n [5] \"Spread:Slope\"  \"Spread:Snow\"   \"Angle:Aspect\"  \"Angle:Slope\"  \n [9] \"Angle:Snow\"    \"Area:Aspect\"   \"Area:Slope\"    \"Area:Snow\"    \n[13] \"Thick:Aspect\"  \"Thick:Slope\"   \"Thick:Snow\"    \"SLA:Aspect\"   \n[17] \"SLA:Slope\"     \"SLA:Snow\"      \"N_mass:Aspect\" \"N_mass:Slope\" \n[21] \"N_mass:Snow\"   \"Seed:Aspect\"   \"Seed:Slope\"    \"Seed:Snow\"    \n```\n:::\n:::\n\n\nBecause we have abundance data, let's run the GLM using the poisson model (log link function) and the negative binomial which may work better when data are overdispersed (e.g., too many zeros, i.e., absences).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDist.stacked <- as.vector(as.matrix(aravo$spe))\nColNames <- colnames(TE)\nTE <- scale(TE) # so that slopes can be compared directly to one another\ncolnames(TE) <- ColNames\nmodel.bilinear.poisson <- glm(Dist.stacked ~ TE,family=\"poisson\")\nlibrary(MASS)\nmodel.bilinear.negBinom <- glm.nb(Dist.stacked  ~ TE)\n```\n:::\n\n\nLet's compare the two models:\n\n::: {.cell}\n\n```{.r .cell-code}\nc(BIC(model.bilinear.poisson),BIC(model.bilinear.negBinom))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9310.771 8784.627\n```\n:::\n:::\n\nThe BIC suggests that negative binomial fits the data better (smaller BIC, better fit).        \n\nModel diagnostics for non-Gaussian models are challenging and often standard tools don't provide a good way to assess quality of models.  Let's check model residuals using the more classic approach. `sppVec` below will be used to create a different color for each species.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a vector of species names compatible with the stacked model:\nsppVec = rep(row.names(aravo$traits),each=nrow(aravo$spe))\nplot(residuals(model.bilinear.negBinom),log(fitted(model.bilinear.negBinom)),col=as.numeric(factor(sppVec)),xlab=\"Fitted values [log scale]\",ylab=\"residuals\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-74-1.png){width=576}\n:::\n:::\n\n\nAs we can see, the plot is pretty bad; and that's a common feature for GLMs.  \n\nDunn and Smyth (1996) developed a new class of residuals that allows a much better way to diagnose whether the model fits the data well.  The package `DHARMa` implements the approach.   A tutorial for this package and the package features can be found at: <a href = \"https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html\"https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html</a>.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"DHARMa\")\nlibrary(\"DHARMa\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThis is DHARMa 0.4.6. For overview type '?DHARMa'. For recent changes, type news(package = 'DHARMa')\n```\n:::\n\n```{.r .cell-code}\nDunnSmyth.res <- simulateResiduals(fittedModel = model.bilinear.negBinom, plot = F)\nplot(DunnSmyth.res$scaledResiduals~log(fitted(model.bilinear.negBinom)),col=as.numeric(factor(sppVec)),xlab=\"Fitted values [log scale]\",ylab=\"residuals\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-75-1.png){width=576}\n:::\n:::\n\n\nAnd now the Q-Q plot to assess residual normality:\n\n::: {.cell}\n\n```{.r .cell-code}\nplotQQunif(DunnSmyth.res)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-76-1.png){width=576}\n:::\n:::\n\n\nJust for illustration, let's compare it with the Q-Q plot for the poisson model which had smaller support:\n\n::: {.cell}\n\n```{.r .cell-code}\nDunnSmyth.res.poisson <- simulateResiduals(fittedModel = model.bilinear.poisson, plot = F)\nplotQQunif(DunnSmyth.res.poisson)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nDHARMa:testOutliers with type = binomial may have inflated Type I error rates for integer-valued distributions. To get a more exact result, it is recommended to re-run testOutliers with type = 'bootstrap'. See ?testOutliers for details\n```\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-77-1.png){width=576}\n:::\n:::\n\nThe poisson model doesn't fit as well the expected line as the negative binomial model.  As such, the negative binomial model fits better also with the assumption of normality.  \n\nWe can use the package `jtools` to create model summaries and visualization for GLMs.  You can find a good introduction to this package here:        \n\n<a href =\"https://cran.r-project.org/web/packages/jtools/vignettes/summ.html\">https://cran.r-project.org/web/packages/jtools/vignettes/summ.html</a>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"jtools\")\n# install.packages(\"ggstance\")\n# install.packages(\"broom.mixed\")\nlibrary(jtools)\nsumm(model.bilinear.negBinom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nError in glm.control(...) : \n  unused argument (family = list(\"Negative Binomial(0.5278)\", \"log\", function (mu) \nlog(mu), function (eta) \npmax(exp(eta), .Machine$double.eps), function (mu) \nmu + mu^2/.Theta, function (y, mu, wt) \n2 * wt * (y * log(pmax(1, y)/mu) - (y + .Theta) * log((y + .Theta)/(mu + .Theta))), function (y, n, mu, wt, dev) \n{\n    term <- (y + .Theta) * log(mu + .Theta) - y * log(mu) + lgamma(y + 1) - .Theta * log(.Theta) + lgamma(.Theta) - lgamma(.Theta + y)\n    2 * sum(term * wt)\n}, function (eta) \npmax(exp(eta), .Machine$double.eps), expression({\n    if (any(y < 0)) stop(\"negative values not allowed for the negative binomial family\")\n    n <- rep(1, nobs)\n    mustart <- y + (y == 0)/6\n}), function (mu) \nall(mu > 0), function (eta) \nTRUE, function (object, nsim) \n{\n    ftd <- fitted(object)\n    rnegbin(nsim * length(ftd), ftd, .Theta)\n}))\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Something went wrong when calculating the pseudo R-squared. Returning NA\ninstead.\n```\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 6150 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> Dist.stacked </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> Generalized linear model </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Family </td>\n   <td style=\"text-align:right;\"> Negative Binomial(0.5278) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Link </td>\n   <td style=\"text-align:right;\"> log </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> 𝛘²(NA) </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (Cragg-Uhler) </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (McFadden) </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> AIC </td>\n   <td style=\"text-align:right;\"> 8609.80 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> BIC </td>\n   <td style=\"text-align:right;\"> 8784.63 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> z val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -1.27 </td>\n   <td style=\"text-align:right;\"> 0.03 </td>\n   <td style=\"text-align:right;\"> -40.67 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEHeight:Aspect </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 0.81 </td>\n   <td style=\"text-align:right;\"> 0.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEHeight:Slope </td>\n   <td style=\"text-align:right;\"> 0.08 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 1.56 </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEHeight:Snow </td>\n   <td style=\"text-align:right;\"> -0.07 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> -0.69 </td>\n   <td style=\"text-align:right;\"> 0.49 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESpread:Aspect </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> 0.56 </td>\n   <td style=\"text-align:right;\"> 0.58 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESpread:Slope </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> 1.18 </td>\n   <td style=\"text-align:right;\"> 0.24 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESpread:Snow </td>\n   <td style=\"text-align:right;\"> -0.38 </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> -3.82 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEAngle:Aspect </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 0.50 </td>\n   <td style=\"text-align:right;\"> 0.62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEAngle:Slope </td>\n   <td style=\"text-align:right;\"> 0.21 </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 2.99 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEAngle:Snow </td>\n   <td style=\"text-align:right;\"> -0.35 </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> -3.52 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEArea:Aspect </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n   <td style=\"text-align:right;\"> 0.36 </td>\n   <td style=\"text-align:right;\"> 0.72 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEArea:Slope </td>\n   <td style=\"text-align:right;\"> 0.01 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> 0.16 </td>\n   <td style=\"text-align:right;\"> 0.87 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEArea:Snow </td>\n   <td style=\"text-align:right;\"> -0.24 </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n   <td style=\"text-align:right;\"> -1.90 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEThick:Aspect </td>\n   <td style=\"text-align:right;\"> -0.01 </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> -0.09 </td>\n   <td style=\"text-align:right;\"> 0.93 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEThick:Slope </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 2.09 </td>\n   <td style=\"text-align:right;\"> 0.04 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEThick:Snow </td>\n   <td style=\"text-align:right;\"> -0.17 </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> -1.91 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESLA:Aspect </td>\n   <td style=\"text-align:right;\"> 0.45 </td>\n   <td style=\"text-align:right;\"> 0.19 </td>\n   <td style=\"text-align:right;\"> 2.43 </td>\n   <td style=\"text-align:right;\"> 0.02 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESLA:Slope </td>\n   <td style=\"text-align:right;\"> -0.31 </td>\n   <td style=\"text-align:right;\"> 0.14 </td>\n   <td style=\"text-align:right;\"> -2.19 </td>\n   <td style=\"text-align:right;\"> 0.03 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESLA:Snow </td>\n   <td style=\"text-align:right;\"> -0.42 </td>\n   <td style=\"text-align:right;\"> 0.15 </td>\n   <td style=\"text-align:right;\"> -2.81 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEN_mass:Aspect </td>\n   <td style=\"text-align:right;\"> -0.60 </td>\n   <td style=\"text-align:right;\"> 0.19 </td>\n   <td style=\"text-align:right;\"> -3.10 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEN_mass:Slope </td>\n   <td style=\"text-align:right;\"> -0.06 </td>\n   <td style=\"text-align:right;\"> 0.15 </td>\n   <td style=\"text-align:right;\"> -0.38 </td>\n   <td style=\"text-align:right;\"> 0.70 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEN_mass:Snow </td>\n   <td style=\"text-align:right;\"> 0.67 </td>\n   <td style=\"text-align:right;\"> 0.15 </td>\n   <td style=\"text-align:right;\"> 4.54 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESeed:Aspect </td>\n   <td style=\"text-align:right;\"> 0.30 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 2.80 </td>\n   <td style=\"text-align:right;\"> 0.01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESeed:Slope </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 2.21 </td>\n   <td style=\"text-align:right;\"> 0.03 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESeed:Snow </td>\n   <td style=\"text-align:right;\"> -0.50 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> -4.39 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: MLE</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\nThe package `jtools` offers a variety of table and graphical outputs and is worth exploring.  Here we will produce a confidence interval plot for each slope.  This will take a moment (one minute or less):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_summs(model.bilinear.negBinom, scale = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nError in glm.control(...) : \n  unused argument (family = list(\"Negative Binomial(0.5278)\", \"log\", function (mu) \nlog(mu), function (eta) \npmax(exp(eta), .Machine$double.eps), function (mu) \nmu + mu^2/.Theta, function (y, mu, wt) \n2 * wt * (y * log(pmax(1, y)/mu) - (y + .Theta) * log((y + .Theta)/(mu + .Theta))), function (y, n, mu, wt, dev) \n{\n    term <- (y + .Theta) * log(mu + .Theta) - y * log(mu) + lgamma(y + 1) - .Theta * log(.Theta) + lgamma(.Theta) - lgamma(.Theta + y)\n    2 * sum(term * wt)\n}, function (eta) \npmax(exp(eta), .Machine$double.eps), expression({\n    if (any(y < 0)) stop(\"negative values not allowed for the negative binomial family\")\n    n <- rep(1, nobs)\n    mustart <- y + (y == 0)/6\n}), function (mu) \nall(mu > 0), function (eta) \nTRUE, function (object, nsim) \n{\n    ftd <- fitted(object)\n    rnegbin(nsim * length(ftd), ftd, .Theta)\n}))\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Something went wrong when calculating the pseudo R-squared. Returning NA\ninstead.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nRegistered S3 methods overwritten by 'broom':\n  method            from  \n  tidy.glht         jtools\n  tidy.summary.glht jtools\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required namespace: broom.mixed\n```\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-79-1.png){width=576}\n:::\n:::\n\n\nOne needs to be careful when interpreting these confidence intervals as they were produced parametrically and they may be biased as we discussed in the section on statistical hypothesis testing.  Again, this is a strong area of development among quantitative ecologists; but we haven't yet derived unified views on this issue.  \n\nWe can also plot the coefficients building:\n\n::: {.cell}\n\n```{.r .cell-code}\ncf <- coefficients(model.bilinear.negBinom)[-1] # removes the intercept\ncfInter <- matrix(t(cf),nrow=ncol(E))\ncolnames(cfInter) <- colnames(T)\nrownames(cfInter) <- colnames(E)\ncfInter\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Height      Spread       Angle        Area        Thick        SLA\nAspect  0.08562528  0.05659044  0.05406318  0.04512061 -0.008000594  0.4512878\nSlope   0.08477186  0.06555292  0.20518548  0.01057746  0.101762893 -0.3083102\nSnow   -0.07428183 -0.37726596 -0.35230429 -0.23652105 -0.174573655 -0.4210057\n            N_mass       Seed\nAspect -0.59525146  0.2977853\nSlope  -0.05644061  0.1137532\nSnow    0.67458707 -0.5011741\n```\n:::\n\n```{.r .cell-code}\n# install.packages(\"lattice\")\nlibrary(lattice)\na <- max(abs(cfInter))\ncolort = colorRampPalette(c(\"blue\",\"white\",\"red\"))\nlevelplot(cfInter, xlab=\"traits\",ylab=\"environment\", col.regions=colort(100), at=seq(-a, a, length=100))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-80-1.png){width=576}\n:::\n:::\n\n\n<hr style=\"border:1px solid gray\"> </hr>       \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Considering main effects of trait and environment, and their interactions - predicting and explaining species distributions**</span></div>  \n\nThe bilinear model estimates and test for the interactions between traits and environmental features in a single model.  That allows for partial slopes to be estimated (i.e., in which the effects of one trait-environment interaction is independent of the others as in standard linear regression models and GLMs). Understanding partial slopes is essential for inference and usually covered in Intro statistics for biologists/ecologists under multiple regression.  A standard definition is \"The partial slope in multiple regression (or GLM) is the slope of the relationship between a predictor variable that is independent of the other predictor variables and the criterion. It is also the regression coefficient for the predictor variable in question.\" (<a href = \"https://onlinestatbook.com/2/glossary/partial_slope.html\">https://onlinestatbook.com/2/glossary/partial_slope.html</a>).            \n  \nNow, we may want to consider also the main effects of each environmental feature and traits in addition to their interactions.  This is the model implemented in Jamil et al. (2013) and Brown et al. (2014).  The Brown model et al. model is:\n\n$${ln(Y_{ij}) = \\beta_0\\ +\\beta_1env_i\\ +\\beta_2env_i^2\\ +\\beta_3spp_j\\ +\\beta_4(env \\times\\ trait)_{ij}\\ }$$\nwhere $\\beta_0$ is the overall intercept for the model, $\\beta_1env_i$ contains the slopes for each environmental variable, the model also consider square terms for the environmental variables $\\beta_2env_i^2$, $\\beta_3spp_j$ contains species-specific intercept terms which allows predictions for each species separately, $\\beta_4(env \\times\\ trait)_{ij}$ contains the slopes for each trait by environment interaction (the 4th corner slopes).  Whereas Brown et al. treated $spp_j$ as fixed, Jamil et al. (2013) treated as random (more on this later). I've followed the formulation notation given in Brown et al. to facilitate understanding their paper; but we could easily change by the notation used in the mixed model selection (following Gelman and Hill 2007).       \n\nBy setting species-specific intercept terms (i.e., $\\beta_3spp_j$) we can predict species in their appropriate scale of abundance variation.  As such, we can use these types of models to predict species distributions.  This sort of modelling is becoming the standard for predicting multiple species because it considers multiple types of predictors (trait, environments, non-linearities) and their interactions.  Single species models, for instance, can't consider trait variation and the interactions of traits and environment.  As such, stacked models are extremely powerful tools even for modelling single species distributions.  \n\nThe Brown et al. model can be fit using the package `mvabund` as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"mvabund\")\nlibrary(mvabund)\nglm.trait.res <- traitglm(as.matrix(aravo$spe),E,T,family=\"negative.binomial\",col.intercepts=TRUE)\nBIC(glm.trait.res)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       l \n8104.818 \n```\n:::\n:::\n\n\nAll coefficients of the model can be retrieved by:\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefficients(glm.trait.res)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         l\n(Intercept)   -1.939671753\nsppAlch.glau  -0.054831143\nsppAlch.pent   0.024330521\nsppAlch.vulg  -0.155929316\nsppAlop.alpi   0.069840352\nsppAndr.brig  -0.144086942\nsppAndr.vita  -0.117405506\nsppAnte.carp  -0.105193294\nsppAnte.dioi  -0.259135963\nsppAnth.alpe  -0.404567216\nsppAnth.nipp  -0.069393787\nsppArni.mont  -0.265964212\nsppAste.alpi  -0.324558310\nsppAven.vers  -0.108786793\nsppBart.alpi  -0.332898371\nsppCamp.sche  -0.008108304\nsppCard.alpi  -0.136528887\nsppCare.foet   0.027908430\nsppCare.parv  -0.174556575\nsppCare.rosa  -0.091371379\nsppCare.rupe  -0.182772040\nsppCare.semp  -0.112095430\nsppCera.cera  -0.171760014\nsppCera.stri  -0.021497460\nsppCirs.acau  -0.188888639\nsppDrab.aizo  -0.118690070\nsppDrya.octo  -0.358279264\nsppErig.unif  -0.059293913\nsppFest.laev  -0.365739677\nsppFest.quad  -0.105113832\nsppFest.viol  -0.058339848\nsppGent.acau  -0.181050369\nsppGent.camp  -0.134520188\nsppGent.vern  -0.044346876\nsppGeum.mont   0.064963289\nsppHeli.sede  -0.217416821\nsppHier.pili  -0.138692435\nsppHomo.alpi  -0.207003373\nsppKobr.myos  -0.028361647\nsppLeon.pyre   0.029558348\nsppLeuc.alpi  -0.003570705\nsppLigu.muto  -0.064014046\nsppLloy.sero  -0.284035626\nsppLotu.alpi  -0.144194010\nsppLuzu.lute  -0.193109208\nsppMinu.sedo   0.021602219\nsppMinu.vern  -0.137286811\nsppMyos.alpe  -0.092884602\nsppOmal.supi   0.033812911\nsppOxyt.camp  -0.233480701\nsppOxyt.lapp  -0.201732614\nsppPhyt.orbi  -0.327727501\nsppPlan.alpi   0.066971460\nsppPoa.alpi    0.095801892\nsppPoa.supi   -0.203286074\nsppPoly.vivi  -0.016324658\nsppPote.aure   0.053779431\nsppPote.cran  -0.126165407\nsppPote.gran  -0.231501706\nsppPuls.vern  -0.096096734\nsppRanu.kuep  -0.020389979\nsppSagi.glab  -0.011366535\nsppSali.herb   0.053863437\nsppSali.reti  -0.286340876\nsppSali.retu  -0.255645078\nsppSali.serp  -0.283448058\nsppSaxi.pani  -0.185168997\nsppScab.luci  -0.331712183\nsppSedu.alpe  -0.065750719\nsppSemp.mont  -0.074418068\nsppSene.inca  -0.162375900\nsppSesl.caer  -0.205203677\nsppSibb.proc   0.019139245\nsppSile.acau  -0.179836450\nsppTara.alpi  -0.250167730\nsppThym.poly  -0.280189375\nsppTrif.alpi  -0.134717635\nsppTrif.badi  -0.322563479\nsppTrif.thal  -0.225527793\nsppVero.alli  -0.293989557\nsppVero.alpi  -0.100779079\nsppVero.bell  -0.011889063\nAspect         0.014997588\nSlope          0.064347175\nSnow          -0.303043451\nAspect.squ     0.013997280\nSlope.squ     -0.047627887\nSnow.squ      -0.274070121\nAspect.Height -0.010645817\nAspect.Spread -0.070752741\nAspect.Angle  -0.083977548\nAspect.Area   -0.040276747\nAspect.Thick  -0.082064700\nAspect.SLA     0.065782084\nAspect.N_mass -0.138709436\nAspect.Seed    0.042758169\nSlope.Height  -0.020464655\nSlope.Spread   0.023128427\nSlope.Angle   -0.018699260\nSlope.Area    -0.027960323\nSlope.Thick   -0.012369639\nSlope.SLA     -0.108694248\nSlope.N_mass   0.021179434\nSlope.Seed     0.014142823\nSnow.Height   -0.209648151\nSnow.Spread    0.049505713\nSnow.Angle    -0.188496204\nSnow.Area     -0.046298194\nSnow.Thick     0.099956790\nSnow.SLA       0.309130472\nSnow.N_mass    0.317287032\nSnow.Seed     -0.169753499\n```\n:::\n:::\n\nThe overall intercept $\\beta_0=-1.9397$, the individual intercept for each species $\\beta_3spp_j$ are the coefficients above starting with `spp`; for instance, the individual slope for `Alch.glau` (1st species in the list) is $\\beta_3spp_1=-0.055$. The slopes for each environmental variable appear under the names we gave.  For instance, the slope for aspect is $\\beta_1env_aspect=0.015$.  Note that `.squ` in the coefficients are the slopes for the squared environmental terms; for instance $\\beta_2env_{snow}^2=-0.274$.  Finally we have the 4th corner slopes.  For instance, $\\beta_4(env \\times\\ trait)_{snow,seed\\_mass}=-0.1698$. Remember that snow here refers to the mean snowmelt date.  As such, communities with large seed masses (in average) are found in sites that have early snowmelt dates compared to sites with late snowmelt dates; these sites have communities that tend to have small seed masses in average.  \n\nLet's understand this model by programming it from scratch.  That's really the best way to understand models; and whenever possible I try to demonstrate them from 'scratch'; not always possible depending on the amount of operations (e.g., mixed models) and our abilities to understand large codes .  But this one is simple enough that we can do it:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn.species <- ncol(aravo$spe)\nn.communities <- nrow(aravo$spe)\nn.env.variables <- ncol(E)\n# repeats each trait to make it compatible (vectorized) with the stacked species distributions\ntraitVec <- T[rep(1:n.species,each=n.communities),]\n# repeats each environmental variable to make it compatible  (vectorized) with the stacked species distributions:\nenvVec <- matrix(rep(t(E),n.species),ncol=NCOL(E),byrow=TRUE)\n# creates an intercept for each species:\nspecies.intercepts <- rep(1:n.species,each=n.communities)\nspecies.intercepts <- as.factor(species.intercepts)\nmod <- as.formula(\"~species.intercepts-1\")\nspecies.intercepts <- model.matrix(mod)[,-1]\n# the interaction terms:\nTE <- kronecker(T, E, make.dimnames = TRUE)\n# combining the predictors in a single matrix:\npreds <- cbind(species.intercepts,envVec,envVec^2,TE)\n# running the model\nmodel.bilinear.negBinom.Brown <- glm.nb(Dist.stacked  ~ preds)\n```\n:::\n\n\nAnd as we can see, they are exactly the same model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBIC(glm.trait.res)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       l \n8104.818 \n```\n:::\n\n```{.r .cell-code}\nBIC(model.bilinear.negBinom.Brown)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8104.818\n```\n:::\n:::\n\n\nWe can easily adapt the graphical and diagnostic outputs for this model as well, but we won't for simplicity. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumm(model.bilinear.negBinom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nError in glm.control(...) : \n  unused argument (family = list(\"Negative Binomial(0.5278)\", \"log\", function (mu) \nlog(mu), function (eta) \npmax(exp(eta), .Machine$double.eps), function (mu) \nmu + mu^2/.Theta, function (y, mu, wt) \n2 * wt * (y * log(pmax(1, y)/mu) - (y + .Theta) * log((y + .Theta)/(mu + .Theta))), function (y, n, mu, wt, dev) \n{\n    term <- (y + .Theta) * log(mu + .Theta) - y * log(mu) + lgamma(y + 1) - .Theta * log(.Theta) + lgamma(.Theta) - lgamma(.Theta + y)\n    2 * sum(term * wt)\n}, function (eta) \npmax(exp(eta), .Machine$double.eps), expression({\n    if (any(y < 0)) stop(\"negative values not allowed for the negative binomial family\")\n    n <- rep(1, nobs)\n    mustart <- y + (y == 0)/6\n}), function (mu) \nall(mu > 0), function (eta) \nTRUE, function (object, nsim) \n{\n    ftd <- fitted(object)\n    rnegbin(nsim * length(ftd), ftd, .Theta)\n}))\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Something went wrong when calculating the pseudo R-squared. Returning NA\ninstead.\n```\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 6150 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> Dist.stacked </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> Generalized linear model </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Family </td>\n   <td style=\"text-align:right;\"> Negative Binomial(0.5278) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Link </td>\n   <td style=\"text-align:right;\"> log </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> 𝛘²(NA) </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (Cragg-Uhler) </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (McFadden) </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> AIC </td>\n   <td style=\"text-align:right;\"> 8609.80 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> BIC </td>\n   <td style=\"text-align:right;\"> 8784.63 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> z val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -1.27 </td>\n   <td style=\"text-align:right;\"> 0.03 </td>\n   <td style=\"text-align:right;\"> -40.67 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEHeight:Aspect </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 0.81 </td>\n   <td style=\"text-align:right;\"> 0.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEHeight:Slope </td>\n   <td style=\"text-align:right;\"> 0.08 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 1.56 </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEHeight:Snow </td>\n   <td style=\"text-align:right;\"> -0.07 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> -0.69 </td>\n   <td style=\"text-align:right;\"> 0.49 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESpread:Aspect </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> 0.56 </td>\n   <td style=\"text-align:right;\"> 0.58 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESpread:Slope </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> 1.18 </td>\n   <td style=\"text-align:right;\"> 0.24 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESpread:Snow </td>\n   <td style=\"text-align:right;\"> -0.38 </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> -3.82 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEAngle:Aspect </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 0.50 </td>\n   <td style=\"text-align:right;\"> 0.62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEAngle:Slope </td>\n   <td style=\"text-align:right;\"> 0.21 </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 2.99 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEAngle:Snow </td>\n   <td style=\"text-align:right;\"> -0.35 </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> -3.52 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEArea:Aspect </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n   <td style=\"text-align:right;\"> 0.36 </td>\n   <td style=\"text-align:right;\"> 0.72 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEArea:Slope </td>\n   <td style=\"text-align:right;\"> 0.01 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> 0.16 </td>\n   <td style=\"text-align:right;\"> 0.87 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEArea:Snow </td>\n   <td style=\"text-align:right;\"> -0.24 </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n   <td style=\"text-align:right;\"> -1.90 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEThick:Aspect </td>\n   <td style=\"text-align:right;\"> -0.01 </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> -0.09 </td>\n   <td style=\"text-align:right;\"> 0.93 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEThick:Slope </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 2.09 </td>\n   <td style=\"text-align:right;\"> 0.04 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEThick:Snow </td>\n   <td style=\"text-align:right;\"> -0.17 </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> -1.91 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESLA:Aspect </td>\n   <td style=\"text-align:right;\"> 0.45 </td>\n   <td style=\"text-align:right;\"> 0.19 </td>\n   <td style=\"text-align:right;\"> 2.43 </td>\n   <td style=\"text-align:right;\"> 0.02 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESLA:Slope </td>\n   <td style=\"text-align:right;\"> -0.31 </td>\n   <td style=\"text-align:right;\"> 0.14 </td>\n   <td style=\"text-align:right;\"> -2.19 </td>\n   <td style=\"text-align:right;\"> 0.03 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESLA:Snow </td>\n   <td style=\"text-align:right;\"> -0.42 </td>\n   <td style=\"text-align:right;\"> 0.15 </td>\n   <td style=\"text-align:right;\"> -2.81 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEN_mass:Aspect </td>\n   <td style=\"text-align:right;\"> -0.60 </td>\n   <td style=\"text-align:right;\"> 0.19 </td>\n   <td style=\"text-align:right;\"> -3.10 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEN_mass:Slope </td>\n   <td style=\"text-align:right;\"> -0.06 </td>\n   <td style=\"text-align:right;\"> 0.15 </td>\n   <td style=\"text-align:right;\"> -0.38 </td>\n   <td style=\"text-align:right;\"> 0.70 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TEN_mass:Snow </td>\n   <td style=\"text-align:right;\"> 0.67 </td>\n   <td style=\"text-align:right;\"> 0.15 </td>\n   <td style=\"text-align:right;\"> 4.54 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESeed:Aspect </td>\n   <td style=\"text-align:right;\"> 0.30 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 2.80 </td>\n   <td style=\"text-align:right;\"> 0.01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESeed:Slope </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 2.21 </td>\n   <td style=\"text-align:right;\"> 0.03 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TESeed:Snow </td>\n   <td style=\"text-align:right;\"> -0.50 </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> -4.39 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: MLE</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\n\nAs mentioned earlier, we can get predicted models per species, making stacked models not only a community model but also considering information from multiple sources for single species distributions as well:\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted.by.species <- matrix(glm.trait.res$fitted,n.communities,n.species)\n```\n:::\n\nPredicted abundance values per species are in columns:\n```\nView(fitted.by.species)\n```\n\n<hr style=\"border:1px solid gray\"> </hr>     \n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**A very brief way to understand mixed models: the Simpson's paradox **</span></div>  \n\nSpecies and sites are not likely to differ from one another randomly but rather have some sites more similar to others (or more different).  We call this a hierarchical structure.  For instance, sites that are more close to one another may have more similar values than sites further way. Or some species may be more similar in abundance than others, and so on. \n\nWhen using linear models and GLMS, researchers often ignore the hierarchical structure of the data (some sites have more similar or differences in total abundances of species, some species have more similar or differences in their total abundances). As such, standard GLMs can generate biased variance estimates and increase the likelihood of committing type I errors (i.e., rejecting the statistical null hypothesis more often than set by alpha, i.e., significance level). \n\nAlthough this is very interesting ecologically, it does bring some inferential challenges (parameter estimation and statistical hypothesis testing) when fitting statistical models. GLMM (Generalized Linear Mixed Models) are then used to deal with these issues. This paper by Harrison et al. (2018) provides a great Introduction to GLLMs for ecologists: <a href = \"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5970551/\">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5970551/</a>.\n\nOne common feature here is that species may differ in the way they are structured by environmental and/or trait variation. This can be well described by the Simpson's paradox (Simpson 1951), which is defined \"as a phenomenon in probability and statistics in which a trend appears in several groups of data but disappears or reverses when the groups are combined.\"           \n\nLet's understand this paradox by simulating some data (code not show here) and graphing it.  This sort of demonstration has become somewhat common when explaining the utility of mixed model. \n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-88-1.png){width=576}\n:::\n:::\n\n\nAt first glance, the influence of temperature on abundance is positive if we consider the variation across all data points independent of the sites.  However, within species, the influence of the environment is negative.  As such, it is obvious that there is variation among species that can't be explained by temperature alone.  As such, we should consider a mixed model with temperature as a fixed factor (measured variable) and species as a random factor.  Obviously one question of interest is why do species vary in their effects of temperature.  But we don't have other predictors that could assist in explaining these differences (e.g., physiology). Perhaps considering traits could assist in determining this variation (more on that later).\n\nThe data was saved in a matrix called `data.Simpson`. For simplicity, we will treat these data as normally distributed. The data were generated assuming normality any way; the goal here is just a demonstration.          \n\nLet's analyze these data with a fixed model using a simple regression:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jtools)\nlm.mod <- lm(abundance ~ scale(temperature),data=data.Simpson)\nsumm(lm.mod,scale = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 100 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> abundance </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> OLS linear regression </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> F(1,98) </td>\n   <td style=\"text-align:right;\"> 15.13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> R² </td>\n   <td style=\"text-align:right;\"> 0.13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Adj. R² </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -0.08 </td>\n   <td style=\"text-align:right;\"> 0.18 </td>\n   <td style=\"text-align:right;\"> -0.48 </td>\n   <td style=\"text-align:right;\"> 0.63 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> `scale(temperature)` </td>\n   <td style=\"text-align:right;\"> 0.69 </td>\n   <td style=\"text-align:right;\"> 0.18 </td>\n   <td style=\"text-align:right;\"> 3.89 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: OLS; Continuous predictors are mean-centered and scaled by 1 s.d.</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\nAs we can see, the overal influence of temperature is positive and significant, explaining 12% of the variation in abundance as a function of temperature (i.e., $R^2=0.12$).        \n\nLet's consider now a mixed effect model that we estimate the variation in intercepts but still assume a common slope for all species.  This is a common procedure in mixed model effects, i.e., starting with the simplest model.  This fixed effect is coded as usually and the random effect is coded as `(1|species)`, where 1 means the intercepts (common way to code the intercept in statistical models).  As such, one intercept per species is estimated.  The `scale=TRUE` in the function `summ` below reports the analysis with standardized predictors.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"lme4\")\nlibrary(lme4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: Matrix\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'Matrix'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:tidyr':\n\n    expand, pack, unpack\n```\n:::\n\n```{.r .cell-code}\nlm.mod.intercept <- lmer(abundance ~ temperature + (1|species),data=data.Simpson)\nsumm(lm.mod.intercept,scale = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 100 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> abundance </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> Mixed effects linear regression </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> AIC </td>\n   <td style=\"text-align:right;\"> 343.74 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> BIC </td>\n   <td style=\"text-align:right;\"> 354.16 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (fixed effects) </td>\n   <td style=\"text-align:right;\"> 0.30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (total) </td>\n   <td style=\"text-align:right;\"> 0.95 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"6\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Fixed Effects</div></th></tr>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> d.f. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -0.08 </td>\n   <td style=\"text-align:right;\"> 1.88 </td>\n   <td style=\"text-align:right;\"> -0.04 </td>\n   <td style=\"text-align:right;\"> 3.94 </td>\n   <td style=\"text-align:right;\"> 0.97 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> temperature </td>\n   <td style=\"text-align:right;\"> -2.84 </td>\n   <td style=\"text-align:right;\"> 0.35 </td>\n   <td style=\"text-align:right;\"> -8.10 </td>\n   <td style=\"text-align:right;\"> 97.70 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup>  p values calculated using Kenward-Roger standard errors and d.f. ; Continuous predictors are mean-centered and scaled by 1 s.d.</td></tr></tfoot>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"3\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Random Effects</div></th></tr>\n  <tr>\n   <th> Group </th>\n   <th> Parameter </th>\n   <th> Std. Dev. </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td> species </td>\n   <td> (Intercept) </td>\n   <td> 4.20 </td>\n  </tr>\n  <tr>\n   <td> Residual </td>\n   <td>  </td>\n   <td> 1.16 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"3\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Grouping Variables</div></th></tr>\n  <tr>\n   <th> Group </th>\n   <th> # groups </th>\n   <th> ICC </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td> species </td>\n   <td> 5 </td>\n   <td> 0.93 </td>\n  </tr>\n</tbody>\n</table>\n`````\n:::\n:::\n\nWow, what a change in the interpretation.  By considering variation in intercepts across species, the fixed effect influence of temperature is now negative (as we should expect).  Note, however, that we had information on a categorical factor, i.e, species, that could be used to estimate random effects related to variation among them.  The variation (standard deviation) of intercepts among species is quite large in contrast to residuals; 4.20 against 1.16, respectively. The explanatory power of variation among intercepts make the $R^2=0.95$ increase dramatically in contrast to the fixed model, demonstrating that the species random effect has a huge effect and ability to improve the model predictive power. We also find the ICC (Intra Class Correlation) which measures how similar the abundance is within groups, i.e., species. The ICC is 0.93, indicating that abundance values are more similar within than among species.               \nThe variation in intercepts can be plotted as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nintercepts <- coefficients(lm.mod.intercept)$species[,\"(Intercept)\"]\nslopes <- coefficients(lm.mod.intercept)$species[,\"temperature\"]\nlines <- data.frame(intercepts,slopes)\nlines[\"species\"] <-  unique(data.Simpson[,\"species\"])\ndata.Simpson$pred <- predict(lm.mod.intercept)\nggplot() +\ngeom_point(data=data.Simpson,aes(x=temperature,y=abundance,color=species),size=1) + \ngeom_abline(aes(intercept = `(Intercept)`, slope = temperature),size = 1.5,as.data.frame(t(fixef(lm.mod.intercept)))) +\ngeom_abline(data = lines, aes(intercept=intercepts, slope=slopes, color=species)) +\ntheme_classic() + \nxlab(\"Temperature\") + ylab(\"log(Abundance)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-91-1.png){width=672}\n:::\n:::\n\nThe black line represents the common model. Since only intercepts were allowed to vary, the species per slope are the same as the fixed model (after controlling for variation across species, which made the overall slope to be negative).     \nFinally, let's estimate the random intercept and slope model.  Here we estimate variation due to differences in intercepts and slopes across species:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.mod.interceptSlope <- lmer(abundance ~ temperature + (1 + temperature|species),data=data.Simpson)\nsumm(lm.mod.interceptSlope,scale = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 100 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> abundance </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> Mixed effects linear regression </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> AIC </td>\n   <td style=\"text-align:right;\"> 336.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> BIC </td>\n   <td style=\"text-align:right;\"> 351.73 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (fixed effects) </td>\n   <td style=\"text-align:right;\"> 0.31 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (total) </td>\n   <td style=\"text-align:right;\"> 0.96 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"6\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Fixed Effects</div></th></tr>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> d.f. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 0.11 </td>\n   <td style=\"text-align:right;\"> 1.75 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> 3.99 </td>\n   <td style=\"text-align:right;\"> 0.95 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> temperature </td>\n   <td style=\"text-align:right;\"> -2.91 </td>\n   <td style=\"text-align:right;\"> 0.84 </td>\n   <td style=\"text-align:right;\"> -3.45 </td>\n   <td style=\"text-align:right;\"> 3.98 </td>\n   <td style=\"text-align:right;\"> 0.03 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup>  p values calculated using Kenward-Roger standard errors and d.f. ; Continuous predictors are mean-centered and scaled by 1 s.d.</td></tr></tfoot>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"3\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Random Effects</div></th></tr>\n  <tr>\n   <th> Group </th>\n   <th> Parameter </th>\n   <th> Std. Dev. </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td> species </td>\n   <td> (Intercept) </td>\n   <td> 3.84 </td>\n  </tr>\n  <tr>\n   <td> species </td>\n   <td> temperature </td>\n   <td> 1.73 </td>\n  </tr>\n  <tr>\n   <td> Residual </td>\n   <td>  </td>\n   <td> 1.05 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"3\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Grouping Variables</div></th></tr>\n  <tr>\n   <th> Group </th>\n   <th> # groups </th>\n   <th> ICC </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td> species </td>\n   <td> 5 </td>\n   <td> 0.93 </td>\n  </tr>\n</tbody>\n</table>\n`````\n:::\n:::\n\n\nThe variation (standard deviation) in intercepts across species in much larger (3.84) than slopes (1.73).  Is the predictive power between the two models significant? In order words, does a model that estimate independent slopes for each species explain more variation than one that only considers variation in intercepts?\nWe can simply compare the BIC of both models:\n\n::: {.cell}\n\n```{.r .cell-code}\nc(BIC(lm.mod),BIC(lm.mod.intercept),BIC(lm.mod.interceptSlope))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 408.7963 356.1764 353.7488\n```\n:::\n:::\n\nThere is more support for the mixed model that considers variation in intercepts and slopes.  One can also estimate the p-value that one model fits better than the other:\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(lm.mod.intercept,lm.mod.interceptSlope)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nrefitting model(s) with ML (instead of REML)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nData: data.Simpson\nModels:\nlm.mod.intercept: abundance ~ temperature + (1 | species)\nlm.mod.interceptSlope: abundance ~ temperature + (1 + temperature | species)\n                      npar    AIC    BIC  logLik deviance  Chisq Df Pr(>Chisq)\nlm.mod.intercept         4 346.41 356.83 -169.21   338.41                     \nlm.mod.interceptSlope    6 340.30 355.93 -164.15   328.30 10.114  2   0.006365\n                        \nlm.mod.intercept        \nlm.mod.interceptSlope **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nFinally, we can plot the intercept and slope variation. The common fixed effect slope has been now estimated by pooling the variation among species, hence it become negative in contrast to the original fixed effect slope.    \n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercepts <- coefficients(lm.mod.interceptSlope)$species[,\"(Intercept)\"]\nslopes <- coefficients(lm.mod.interceptSlope)$species[,\"temperature\"]\nlines <- data.frame(intercepts,slopes)\nlines[\"species\"] <-  unique(data.Simpson[,\"species\"])\ndata.Simpson$pred <- predict(lm.mod.intercept)\nggplot() +\ngeom_point(data=data.Simpson,aes(x=temperature,y=abundance,color=species),size=2) + \ngeom_abline(aes(intercept = `(Intercept)`, slope = temperature),size = 2,as.data.frame(t(fixef(lm.mod.interceptSlope)))) +\ngeom_abline(data = lines, aes(intercept=intercepts, slope=slopes, color=species),size = 2) +\ntheme_classic() + \nxlab(\"Temperature\") + ylab(\"log(Abundance)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-95-1.png){width=672}\n:::\n:::\n\n\n<span style=\"color:firebrick\">An extreme example pf the Simpson's paradox</span>\n\nLet's consider (just visually) an even more extreme case.  The fixed effect is very strong but the within species effect is almost zero. Hopefully the \"Simpson's\" examples here provide a good intuition on the importance of mixed models.  \n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-97-1.png){width=576}\n:::\n:::\n\n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Our first GLMM applied to the fourth corner problem treating species as a random effect - the MLML1 model**</span></div>  \n\nThere are different ways that we can account for the potential random effects in community ecology data.  Here we will review a few of the latest developments.       \n\nMLM stands for multilevel (i.e., hierarchical) models (MLM).  The simplest of these models is the one introduced by Pollock et al. (2012) and is often referred in the ecological literature as MLM1 (see Miller et al. 2018).  The model has the following form (following the notation of Gelman and Hill 2007; as in Miller et al. 2018).  This is a model that considers species as a random effect while estimating variation in both intercepts and slopes as the last model in the previous session (Simpson's paradox)\n\n$${ln(Y_{i}) = \\alpha\\ +a_{spp[i]}\\ +\\beta_{12}env_{site[i]}\\times trait_{spp[i]} + (\\beta_1+c_{spp[i]})env_{site[i]}+e_i}$$\n$a,c \\sim Gaussian(0,\\sigma_a^2,\\sigma_c^2,\\rho_{ac})$\n$e \\sim Gaussian(0,\\sigma_e^2)$\n\nNote that we changed the notation of Brown et al. $ij$ that served as an index for the $i^{th}$ site and $j^{th}$ species to simply one index $i$ since we are using a stacked model anyway, i.e., only rows for $Y_{i}$ and one column (i.e., stacked species distributions).  As such, the functions $spp[i]$ and $site[i]$ map row i onto the corresponding species and sites. $\\beta_{12}$ contains the slopes for the interactions between environment and trait.  The fixed effect $\\alpha$ gives the overall average abundance of species among sites (one overall intercept), and the fixed effect $\\beta_{1}$ gives the mean response of species to the different environmental variables. Random effect $a_{spp[i]}$ allows different species to have different overall abundance (i.e., sum of abundances across species; random intercept model across species), and random effect $c_{spp[i]}$ allows different species to have different responses to the environmental variables (i.e., random slope model across species). $a_{spp[i]}$ and $c_{spp[i]}$ have means zero and variances $\\sigma_a^2$ and $\\sigma_c^2$ (referred as to hyperparameters in mixed model lingo), with $\\rho_{ac}$ denoting the correlation between $a_{spp[i]}$ and $c_{spp[i]}$ (i.e., species intercepts and species slopes for the environment can correlate). Finally,random effect $e_i$ gives observation-level variance; this is necessary here to allow for overdispersion (Harisson, 2014).  We can also use the negative binomial as we saw earlier. Note that we are assuming hierarchical variation in variance and not covariance (e.g., phylogenetic and spatial autocorrelation). One step at the time. \n\nLet's start by setting an appropriate data structure to run the mixed model.  To make the coding more manageable we will consider here only one trait and one environment.  The code can be easily generalized for multiple traits and environments.  We found early a strong interaction between seed mass and snow in which species with greater seed mass tended to be found in sites with small levels of snow (i.e., a negative correlation between snow and seed mass).\n\nFor simplicity, let's load the `aravo` data again:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ade4)\ndata(aravo)\nE <- aravo$env[,c(\"Aspect\",\"Slope\",\"Snow\")]\nE <- as.matrix(E)\nT <- as.matrix(aravo$trait)\nDist.stacked <- as.vector(as.matrix(aravo$spe))\nn.species <- ncol(aravo$spe)\nn.communities <- nrow(aravo$spe)\nn.env.variables <- ncol(E)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# to code for observation-level variance:\nobs <- 1:(n.species*n.communities)\n# to code for species (as we saw earlier to plot residuals):\nspecies <- rep(row.names(aravo$traits),each=nrow(aravo$spe))\nsites <- rep(row.names(aravo$spe),each=ncol(aravo$spe))\n# standardizing the data:\nseed.mass <- scale(T[rep(1:n.species,each=n.communities),\"Seed\"])\nsnow.melt.days <- scale(matrix(rep(t(E[,\"Snow\"]),n.species),ncol=1,byrow=TRUE))\ndata.df <- data.frame(abundance=Dist.stacked,snow.melt.days,seed.mass,species,sites,obs)\n```\n:::\n\nLet's see the data frame:\n```\nView(data.df)\n```\n\nLet's start by fitting a glm:\n\n::: {.cell}\n\n```{.r .cell-code}\nglm.mod <- glm(abundance ~ snow.melt.days + snow.melt.days:seed.mass,data=data.df, family = \"poisson\")\nsumm(glm.mod,scale = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 6150 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> abundance </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> Generalized linear model </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Family </td>\n   <td style=\"text-align:right;\"> poisson </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Link </td>\n   <td style=\"text-align:right;\"> log </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> 𝛘²(2) </td>\n   <td style=\"text-align:right;\"> 56.18 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (Cragg-Uhler) </td>\n   <td style=\"text-align:right;\"> 0.01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (McFadden) </td>\n   <td style=\"text-align:right;\"> 0.01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> AIC </td>\n   <td style=\"text-align:right;\"> 9421.91 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> BIC </td>\n   <td style=\"text-align:right;\"> 9442.08 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> z val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -1.17 </td>\n   <td style=\"text-align:right;\"> 0.02 </td>\n   <td style=\"text-align:right;\"> -50.74 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> snow.melt.days </td>\n   <td style=\"text-align:right;\"> -0.10 </td>\n   <td style=\"text-align:right;\"> 0.02 </td>\n   <td style=\"text-align:right;\"> -4.20 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> snow.melt.days:seed.mass </td>\n   <td style=\"text-align:right;\"> -0.14 </td>\n   <td style=\"text-align:right;\"> 0.02 </td>\n   <td style=\"text-align:right;\"> -6.39 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: MLE; Continuous predictors are mean-centered and scaled by 1 s.d.</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\nDespite the very low $R^2=0.01$, the coefficiences are all significant and negative. \n\nLet's run the model.  Below, both intercepts (coded as 1) and slopes for snow.melt.days (coded as env) are allowed to vary among species (i.e., (1 + env|species)) and we also allow\n\n::: {.cell}\n\n```{.r .cell-code}\nMLM1.mod <- glmer(abundance ~ snow.melt.days + snow.melt.days:seed.mass + (1 + snow.melt.days|species) + (1 | obs), family = \"poisson\", control=glmerControl(calc.derivs=F), nAGQ = 0, data=data.df)\nsumm(MLM1.mod,scale = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 6150 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> abundance </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> Mixed effects generalized linear model </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Family </td>\n   <td style=\"text-align:right;\"> poisson </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Link </td>\n   <td style=\"text-align:right;\"> log </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> AIC </td>\n   <td style=\"text-align:right;\"> 7335.48 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> BIC </td>\n   <td style=\"text-align:right;\"> 7382.55 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (fixed effects) </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Pseudo-R² (total) </td>\n   <td style=\"text-align:right;\"> 0.65 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"5\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Fixed Effects</div></th></tr>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> z val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -2.12 </td>\n   <td style=\"text-align:right;\"> 0.17 </td>\n   <td style=\"text-align:right;\"> -12.37 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> snow.melt.days </td>\n   <td style=\"text-align:right;\"> -0.72 </td>\n   <td style=\"text-align:right;\"> 0.13 </td>\n   <td style=\"text-align:right;\"> -5.51 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> snow.melt.days:seed.mass </td>\n   <td style=\"text-align:right;\"> -0.08 </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> -0.84 </td>\n   <td style=\"text-align:right;\"> 0.40 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup>  ; Continuous predictors are mean-centered and scaled by 1 s.d.</td></tr></tfoot>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"3\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Random Effects</div></th></tr>\n  <tr>\n   <th> Group </th>\n   <th> Parameter </th>\n   <th> Std. Dev. </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td> obs </td>\n   <td> (Intercept) </td>\n   <td> 0.47 </td>\n  </tr>\n  <tr>\n   <td> species </td>\n   <td> (Intercept) </td>\n   <td> 1.46 </td>\n  </tr>\n  <tr>\n   <td> species </td>\n   <td> snow.melt.days </td>\n   <td> 1.08 </td>\n  </tr>\n</tbody>\n</table> <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"3\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Grouping Variables</div></th></tr>\n  <tr>\n   <th> Group </th>\n   <th> # groups </th>\n   <th> ICC </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td> obs </td>\n   <td> 6150 </td>\n   <td> 0.07 </td>\n  </tr>\n  <tr>\n   <td> species </td>\n   <td> 82 </td>\n   <td> 0.63 </td>\n  </tr>\n</tbody>\n</table>\n`````\n:::\n:::\n\nThe variation among observations (residuals) is not relevant here; we used it to allow for potential overdispersion in abundance (i.e., variance of abundance much greater than the mean).  Note that both the intercept and slopes contribute more or less to the same amount of variation (intercept sd=1.46 and slopes = 1.08), indicating that an intercept and slope mixed model is the most appropriate model. We could have fit the two models and tested as before we saw early in the Simpson's paradox section.  Note the huge increase in $R^2=0.65$, demonstrating that considering a random structure is much better.  The coefficient of `snow.melt.days` remains negative indicating that most species and their variation are negative despite the potential for some species to increase their abundances for large values of snow.melt.days.  We will see this below. \n\nThe residual against the predicted values provide a good indication that the model is appropriate:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DHARMa)\nDunnSmyth.res <- simulateResiduals(fittedModel = MLM1.mod, plot = F)\nplot(DunnSmyth.res$scaledResiduals~log(fitted(MLM1.mod)),col=as.numeric(factor(species)),xlab=\"Fitted values [log scale]\",ylab=\"residuals\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-102-1.png){width=576}\n:::\n:::\n\n\nAnd now the Q-Q plot to assess residual normality:\n\n::: {.cell}\n\n```{.r .cell-code}\nplotQQunif(DunnSmyth.res)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nDHARMa:testOutliers with type = binomial may have inflated Type I error rates for integer-valued distributions. To get a more exact result, it is recommended to re-run testOutliers with type = 'bootstrap'. See ?testOutliers for details\n```\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-103-1.png){width=576}\n:::\n:::\n\nNote that the Kolmogorov-Smirnov (KS) provides indication that the residuals cannot be assumed to be normal. That said, the distribution of residuals looks somewhat on the expected.  The KS becomes quite significant because of the large number of data points.  Finally, GLMs and GLMMs tend to be quite robust even when residuals are not normal.\n\nIntercepts in a poisson model are log of species abundances not explained by the predictors model, i.e., when we set them \"manually\" to take values of zero.  Perhaps some sites are more productive than others and we did not measure trait or environmental variables that could account for the slope and intercept variation variation; but the random effects is telling us that there is something we are potentially missing to explain their variation.           \n\nMoreover, the random effect indicates that species slopes for the environment are strongly and positively correlated with the species intercepts ($\\rho_{ac}=0.73$).  We can plot the intercepts against slopes:\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(coefficients(MLM1.mod)$species[,\"(Intercept)\"],coefficients(MLM1.mod)$species[,\"snow.melt.days\"],xlab=\"species intercepts\", ylab=\"species environmental slopes\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-104-1.png){width=576}\n:::\n:::\n\n\n$\\rho_{ac}$ does not appear in summ(MLM1.mod) but can be found in `summary(MLM1.mod)` intead or calculated directly:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(MLM1.mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGeneralized linear mixed model fit by maximum likelihood (Adaptive\n  Gauss-Hermite Quadrature, nAGQ = 0) [glmerMod]\n Family: poisson  ( log )\nFormula: abundance ~ snow.melt.days + snow.melt.days:seed.mass + (1 +  \n    snow.melt.days | species) + (1 | obs)\n   Data: data.df\nControl: glmerControl(calc.derivs = F)\n\n     AIC      BIC   logLik deviance df.resid \n  7335.5   7382.6  -3660.7   7321.5     6143 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.6289 -0.4400 -0.2650 -0.0639  7.6016 \n\nRandom effects:\n Groups  Name           Variance Std.Dev. Corr\n obs     (Intercept)    0.2221   0.4712       \n species (Intercept)    2.1201   1.4560       \n         snow.melt.days 1.1671   1.0803   0.73\nNumber of obs: 6150, groups:  obs, 6150; species, 82\n\nFixed effects:\n                         Estimate Std. Error z value Pr(>|z|)    \n(Intercept)              -2.11504    0.17095 -12.372  < 2e-16 ***\nsnow.melt.days           -0.71798    0.13037  -5.507 3.64e-08 ***\nsnow.melt.days:seed.mass -0.07552    0.09024  -0.837    0.403    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) snw.m.\nsnw.mlt.dys 0.730        \nsnw.mlt.d:. 0.010  0.015 \n```\n:::\n\n```{.r .cell-code}\ncor(coefficients(MLM1.mod)$species[,\"(Intercept)\"],coefficients(MLM1.mod)$species[,\"snow.melt.days\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7163168\n```\n:::\n:::\n\n\nAlthough the fixed-only effect model run earlier (glm.mod) indicated a significant correlation between snowmelt date and seed mass in driving species distributions, this effect is no longer relevant once the random effects are considered:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(glm.mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = abundance ~ snow.melt.days + snow.melt.days:seed.mass, \n    family = \"poisson\", data = data.df)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.2804  -0.7946  -0.7868  -0.6822   4.3659  \n\nCoefficients:\n                         Estimate Std. Error z value Pr(>|z|)    \n(Intercept)              -1.16767    0.02301 -50.744  < 2e-16 ***\nsnow.melt.days           -0.09714    0.02313  -4.199 2.68e-05 ***\nsnow.melt.days:seed.mass -0.14286    0.02237  -6.387 1.70e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 6552.0  on 6149  degrees of freedom\nResidual deviance: 6495.8  on 6147  degrees of freedom\nAIC: 9421.9\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n:::\n\nThis indicates that the random variation across species can account for the initial relationship between snow.melt.days and seed mass. Note that the importance of snow.melt.days remains relevant in driving species abundances across sites, but (again) not its interaction with seed mass.    \n\nLet's plot regression models per species:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercepts <- coefficients(MLM1.mod)$species[,\"(Intercept)\"]\nslopes <- coefficients(MLM1.mod)$species[,\"snow.melt.days\"]\nlines <- data.frame(intercepts,slopes)\nlines[\"species\"] <-  unique(data.df[,\"species\"])\ndata.df$pred <- predict(MLM1.mod)\nggplot(data=data.df) +\ngeom_point(data=data.df,aes(x=snow.melt.days,y=pred,color=species),size=1) + \ngeom_abline(data = lines, aes(intercept=intercepts, slope=slopes, color=species),size = 2) +\ngeom_abline(aes(intercept = `(Intercept)`, slope = snow.melt.days),size = 2,as.data.frame(t(fixef(MLM1.mod)))) +\ntheme_classic() + \nxlab(\"snow.melt.days\") + ylab(\"log(Abundance)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-107-1.png){width=672}\n:::\n:::\n\n\n\nFinally, the GLMM has good predictive power (relative smaller confidence intervals and large $R^2=0.51$:\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"ggeffects\")\nlibrary(ggeffects)\nplot(ggpredict(MLM1.mod, \"snow.melt.days\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-108-1.png){width=672}\n:::\n:::\n\n\nFinally, as we discussed during the workshop, one needs to be careful while interpreting the significance of interactions between trait and environment.  There are bootstrap-based developments to do that for the MLML1 model but they have been show to have inflated type I errors (Miller et al. 2019).\n\nFunction `glmer.nb` could have been used to fit the model using the negative binomial family instead.\n\nHere is a good and simple introduction to mixed models for poisson regression:     \n<a href = \"https://stats.idre.ucla.edu/r/faq/random-coefficient-poisson-models/         \">https://stats.idre.ucla.edu/r/faq/random-coefficient-poisson-models/</a>\n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Our second GLMM applied to the fourth corner problem treating species and sites as random effects - the MLML2 model**</span></div>  \n\nJamil et al. (2013) implemented a mixed model version in which in contrast to MLM1, it adds a fixed effect term for traits is included in the model (as in Brown et al. 2014) and also an additional random effect (intercepts) for site:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMLM2.mod <- glmer(abundance ~ snow.melt.days * seed.mass + (1 + snow.melt.days|species) + (1 | sites) + (1 | obs), family = \"poisson\", control=glmerControl(calc.derivs=F), nAGQ = 0, data=data.df)\nsummary(MLM2.mod,scale = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in summary.merMod(MLM2.mod, scale = TRUE): additional arguments ignored\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nGeneralized linear mixed model fit by maximum likelihood (Adaptive\n  Gauss-Hermite Quadrature, nAGQ = 0) [glmerMod]\n Family: poisson  ( log )\nFormula: abundance ~ snow.melt.days * seed.mass + (1 + snow.melt.days |  \n    species) + (1 | sites) + (1 | obs)\n   Data: data.df\nControl: glmerControl(calc.derivs = F)\n\n     AIC      BIC   logLik deviance df.resid \n  7264.1   7324.6  -3623.0   7246.1     6141 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.5851 -0.4284 -0.2557 -0.0732  8.9436 \n\nRandom effects:\n Groups  Name           Variance Std.Dev. Corr\n obs     (Intercept)    0.1472   0.3837       \n species (Intercept)    1.6523   1.2854       \n         snow.melt.days 1.0169   1.0084   0.71\n sites   (Intercept)    0.4344   0.6591       \nNumber of obs: 6150, groups:  obs, 6150; species, 82; sites, 75\n\nFixed effects:\n                         Estimate Std. Error z value Pr(>|z|)    \n(Intercept)               -2.1239     0.1708 -12.436  < 2e-16 ***\nsnow.melt.days            -0.6805     0.1228  -5.543 2.97e-08 ***\nseed.mass                 -0.2050     0.1634  -1.255    0.210    \nsnow.melt.days:seed.mass  -0.1134     0.1281  -0.885    0.376    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) snw.m. sd.mss\nsnw.mlt.dys 0.630               \nseed.mass   0.022  0.029        \nsnw.mlt.d:. 0.023  0.031  0.680 \n```\n:::\n:::\n\n\nLet's test the fit difference between MLM1 and MLM2:\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(MLM1.mod,MLM2.mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: data.df\nModels:\nMLM1.mod: abundance ~ snow.melt.days + snow.melt.days:seed.mass + (1 + snow.melt.days | species) + (1 | obs)\nMLM2.mod: abundance ~ snow.melt.days * seed.mass + (1 + snow.melt.days | species) + (1 | sites) + (1 | obs)\n         npar    AIC    BIC  logLik deviance  Chisq Df Pr(>Chisq)    \nMLM1.mod    7 7335.5 7382.6 -3660.7   7321.5                         \nMLM2.mod    9 7264.1 7324.6 -3623.0   7246.1 75.406  2  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nc(BIC(MLM1.mod),BIC(MLM2.mod))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7382.551 7324.594\n```\n:::\n:::\n\n\nWe won't diagnostics here for brevity and the code for the MLM1 can be easily adapted here.          \n\nAlthough the fixed effects for the trait (seed mass) and interaction (seed mass and snow.melt.day) were not significant, the random effect standard deviation for site is relative large (0.66) and improved the predictive power for abundances across species.\n\n<div style=\"text-align:center\"><span style=\"color:firebrick\">**Our last GLMM applied to the fourth corner problem treating species and sites as random effects - the MLML3 model**</span></div>  \n\nter Braak (2019) proposed yet another version that seems to work better than the previous ones.  \n\n::: {.cell}\n\n```{.r .cell-code}\nMLM3.mod <- glmer(abundance ~ snow.melt.days * seed.mass + (1 + snow.melt.days|species) + (1 + seed.mass|sites) + (1 | obs), family = \"poisson\", control=glmerControl(calc.derivs=F), nAGQ = 0, data=data.df)\n```\n:::\n\n\nLet's test the fit difference between MLM2 and MLM3:\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(MLM2.mod,MLM3.mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: data.df\nModels:\nMLM2.mod: abundance ~ snow.melt.days * seed.mass + (1 + snow.melt.days | species) + (1 | sites) + (1 | obs)\nMLM3.mod: abundance ~ snow.melt.days * seed.mass + (1 + snow.melt.days | species) + (1 + seed.mass | sites) + (1 | obs)\n         npar    AIC    BIC  logLik deviance  Chisq Df Pr(>Chisq)\nMLM2.mod    9 7264.1 7324.6 -3623.0   7246.1                     \nMLM3.mod   11 7267.0 7341.0 -3622.5   7245.0 1.0759  2     0.5839\n```\n:::\n\n```{.r .cell-code}\nc(BIC(MLM2.mod),BIC(MLM3.mod))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7324.594 7340.967\n```\n:::\n:::\n\n\nFor these data, the MLM3 does not improve the MLM2.  \n\n<span style=\"font-size:1em;\">**This is not the end - we will keep updating this page after the workshop**</span>       \n<span style=\"color:firebrick\">**References (still being filled):**</span>\n\nAM Brown, DI Warton, NR Andrew, M Binns, G Cassis, H Gibb\nMethods in Ecology and Evolution 5 (4), 344-352\n\nCholer, P. (2005) Consistent shifts in Alpine plant traits along a mesotopographical gradient. Arctic, Antarctic, and Alpine Research, 37,444–453.\n\nDray, S., & Legendre, P. (2008) Testing the species traits-environment relationships : The fourth-corner problem revisited. Ecology, 89, 3400–3412.\n\nDunn, KP & Smyth GK (1996) Randomized quantile residuals. Journal of Computational and Graphical Statistics, 5, 1-10.\n\nGabriel, KR. (1998) Generalised bilinear regression. Biometrika, 85, 689-700.\n\nGelman, A & Hill, J (2007). Data analysis using regression and multi-level/hierarchical models. New York, NY: Cambridge University Press.\n\nHarrison, XA (2014). Using observation-level random effects to model overdispersion in count data in ecology and evolution. PeerJ, 2, e616.\n\nJamil, T., Ozinga, W. A., Kleyer, M., & ter Braak, C. J. F. (2013). Selecting traits that explain species-environment relationships: A generalized linear mixed model approach. Journal of Vegetation Science, 24, 988–1000. \n\nPeres-Neto, P. R., Dray, S., & ter Braak, C. J. F. (2017). Linking trait variation to the environment: Critical issues with community-weighted mean correlation resolved by the fourth-corner approach. Ecography, 40, 806–816.\n\nPollock, L. J., Morris, W. K., & Vesk, P. A. (2012). The role of functional traits in species distributions revealed through a hierarchical model. Ecography, 35, 716–725. \n\nSimpson, EH (1951). The Interpretation of Interaction in Contingency Tables. Journal of the Royal Statistical Society, Series B., 13, 238–241.\n\nter Braak, CJF, Cormont, A. & Dray, S. (2012). Improved testing of species traits–environment relationships in the fourth‐corner problem. Ecology, 93, 1525-1526.\n\nter Braak, CJF & Looman, CWN. (1986). Weighted averaging, logistic regression and the Gaussian response model. Plant Ecology, 65, 3-11.\n\n<span style=\"color:firebrick\">**useful sites for GLMs (will also expand on this later on):**</span>\n\n- Beyond Multiple Linear Regression: \n  <a href = \"https://bookdown.org/roback/bookdown-BeyondMLR/\">https://bookdown.org/roback/bookdown-BeyondMLR/</a>\n  \n\n\n\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}